import { Product } from "react-sigma-chatbox";

export const productList: Product[] = [
  {
    id: 6,
    name: "iPhone 15",
    brand: "Apple",
    brandId: "apple",
    price: 16713112,
    originalPrice: 17970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
    description:
      "iPhone 15 là mẫu iPhone cân bằng giữa hiệu năng, camera và thiết kế. Camera 48MP cho chất lượng ảnh tốt trong nhiều điều kiện, chip A16 đủ mạnh cho mọi tác vụ hàng ngày và chơi game phổ biến.",
    rating: 4.1,
    reviews: 65,
    discount: 7,
    isHot: true,
  },
  {
    id: 10,
    name: "iPhone SE (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 4471220,
    originalPrice: 5960000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg",
    description:
      "iPhone SE (2022) là mẫu iPhone nhỏ gọn với chip A15 mạnh mẽ, mang lại hiệu năng cao trong thiết kế truyền thống. Phù hợp người thích Touch ID và máy nhỏ dễ cầm.",
    rating: 4.8,
    reviews: 64,
    discount: 25,
    isHot: true,
  },
  {
    id: 12,
    name: "iPhone 12 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 10854272,
    originalPrice: 14100000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro--.jpg",
    description:
      "iPhone 12 Pro là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 2815mAh.",
    rating: 4.1,
    reviews: 116,
    discount: 23,
    isHot: false,
  },
  {
    id: 13,
    name: "iPhone 13 mini",
    brand: "Apple",
    brandId: "apple",
    price: 9124064,
    originalPrice: 12500000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-mini.jpg",
    description:
      "iPhone 13 mini là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2438mAh.",
    rating: 4.9,
    reviews: 51,
    discount: 27,
    isHot: true,
  },
  {
    id: 14,
    name: "iPhone 14 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 14368959,
    originalPrice: 19960000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-plus.jpg",
    description:
      "iPhone 14 Plus là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 4323mAh.",
    rating: 4.0,
    reviews: 456,
    discount: 28,
    isHot: false,
  },
  {
    id: 16,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 25593880,
    originalPrice: 33240000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
    description:
      "iPhone 15 Pro Max là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 4441mAh.",
    rating: 4.9,
    reviews: 370,
    discount: 23,
    isHot: false,
  },
  {
    id: 18,
    name: "iPhone 16e",
    brand: "Apple",
    brandId: "apple",
    price: 17237324,
    originalPrice: 18140000,
    image:
      "https://cdn.tgdd.vn/Products/Images/42/334864/iphone-16e-den-thumb-600x600.jpg",
    description:
      "iPhone 16e là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 3279mAh.",
    rating: 5,
    reviews: 63,
    discount: 5,
    isHot: true,
  },
  {
    id: 19,
    name: "iPhone 16 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 24535896,
    originalPrice: 27880000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg",
    description:
      "iPhone 16 Plus là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 4674mAh.",
    rating: 4.6,
    reviews: 399,
    discount: 12,
    isHot: true,
  },
  {
    id: 20,
    name: "iPhone 14",
    brand: "Apple",
    brandId: "apple",
    price: 11995204,
    originalPrice: 12630000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
    description:
      "iPhone 14 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 3279mAh.",
    rating: 5,
    reviews: 336,
    discount: 5,
    isHot: false,
  },
  {
    id: 22,
    name: "iPhone 12 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 13073538,
    originalPrice: 15380000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro-max-.jpg",
    description:
      "iPhone 12 Pro Max là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 3687mAh.",
    rating: 4.4,
    reviews: 281,
    discount: 15,
    isHot: false,
  },
  {
    id: 24,
    name: "iPhone 12",
    brand: "Apple",
    brandId: "apple",
    price: 7246460,
    originalPrice: 10210000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg",
    description:
      "iPhone 12 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2815mAh.",
    rating: 4.9,
    reviews: 465,
    discount: 29,
    isHot: false,
  },
  {
    id: 25,
    name: "iPhone 16",
    brand: "Apple",
    brandId: "apple",
    price: 21078872,
    originalPrice: 25400000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
    description:
      "iPhone 16 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 3561mAh.",
    rating: 4.6,
    reviews: 291,
    discount: 17,
    isHot: false,
  },
  {
    id: 26,
    name: "iPhone 16 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 27135680,
    originalPrice: 37170000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
    description:
      "iPhone 16 Pro là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3582mAh.",
    rating: 5,
    reviews: 244,
    discount: 27,
    isHot: true,
  },
  {
    id: 27,
    name: "iPhone 15 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 22171084,
    originalPrice: 27040000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg",
    description:
      "iPhone 15 Pro là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3274mAh.",
    rating: 4.5,
    reviews: 14,
    discount: 18,
    isHot: false,
  },
  {
    id: 28,
    name: "iPhone 15 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 20503164,
    originalPrice: 24700000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-plus-.jpg",
    description:
      "iPhone 15 Plus là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 4383mAh.",
    rating: 4.6,
    reviews: 466,
    discount: 17,
    isHot: true,
  },
  {
    id: 32,
    name: "iPhone 13",
    brand: "Apple",
    brandId: "apple",
    price: 10422568,
    originalPrice: 13540000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
    description:
      "iPhone 13 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3240mAh.",
    rating: 4.1,
    reviews: 410,
    discount: 23,
    isHot: true,
  },
  {
    id: 33,
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 15078495,
    originalPrice: 16570000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro-max.jpg",
    description:
      "iPhone 13 Pro Max là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4352mAh.",
    rating: 5,
    reviews: 422,
    discount: 9,
    isHot: false,
  },
  {
    id: 38,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 33765111,
    originalPrice: 35540000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    description:
      "iPhone 16 Pro Max là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 4685mAh.",
    rating: 4.4,
    reviews: 465,
    discount: 5,
    isHot: false,
  },
  {
    id: 39,
    name: "iPhone 14 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 16928964,
    originalPrice: 17820000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg",
    description:
      "iPhone 14 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 3200mAh.",
    rating: 4.8,
    reviews: 475,
    discount: 5,
    isHot: true,
  },
  {
    id: 42,
    name: "iPhone 12 mini",
    brand: "Apple",
    brandId: "apple",
    price: 6166891,
    originalPrice: 7810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-mini.jpg",
    description:
      "iPhone 12 mini là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2227mAh.",
    rating: 4.2,
    reviews: 147,
    discount: 21,
    isHot: false,
  },
  {
    id: 44,
    name: "iPhone 13 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 13814528,
    originalPrice: 16250000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
    description:
      "iPhone 13 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 3095mAh.",
    rating: 5,
    reviews: 498,
    discount: 15,
    isHot: false,
  },
  {
    id: 51,
    name: "iPhone 11 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 7400640,
    originalPrice: 9870000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max-.jpg",
    description:
      "iPhone 11 Pro là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3046mAh.",
    rating: 4.3,
    reviews: 279,
    discount: 25,
    isHot: false,
  },
  {
    id: 53,
    name: "iPhone 11 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 9106179,
    originalPrice: 11980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro.jpg",
    description:
      "iPhone 11 Pro Max là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3969mAh.",
    rating: 5,
    reviews: 190,
    discount: 24,
    isHot: true,
  },
  {
    id: 55,
    name: "Galaxy Z Flip7",
    brand: "Samsung",
    brandId: "samsung",
    price: 28687964,
    originalPrice: 32230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip7.jpg",
    description:
      "Galaxy Z Flip7 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4300mAh.",
    rating: 5,
    reviews: 21,
    discount: 11,
    isHot: false,
  },
  {
    id: 56,
    name: "Galaxy M36",
    brand: "Samsung",
    brandId: "samsung",
    price: 5101658,
    originalPrice: 6990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m36.jpg",
    description:
      "Galaxy M36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 297,
    discount: 27,
    isHot: false,
  },

  {
    id: 58,
    name: "Galaxy A26",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 6300000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a26.jpg",
    description:
      "Galaxy A26 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 478,
    discount: 7,
    isHot: false,
  },
  {
    id: 59,
    name: "Galaxy M06",
    brand: "Samsung",
    brandId: "samsung",
    price: 2769338,
    originalPrice: 3180000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m06-5g.jpg",
    description:
      "Galaxy M06 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 453,
    discount: 13,
    isHot: true,
  },
  {
    id: 60,
    name: "Galaxy A56",
    brand: "Samsung",
    brandId: "samsung",
    price: 9096620,
    originalPrice: 12810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a56-.jpg",
    description:
      "Galaxy A56 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 329,
    discount: 29,
    isHot: false,
  },
  {
    id: 61,
    name: "Galaxy F16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3495273,
    originalPrice: 4920000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f16-5g.jpg",
    description:
      "Galaxy F16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 24,
    discount: 29,
    isHot: true,
  },
  {
    id: 62,
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 27721564,
    originalPrice: 29180000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra-sm-s938.jpg",
    description:
      "Galaxy S25 Ultra là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 106,
    discount: 5,
    isHot: false,
  },
  {
    id: 63,
    name: "Galaxy F36",
    brand: "Samsung",
    brandId: "samsung",
    price: 4955888,
    originalPrice: 5220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f36.jpg",
    description:
      "Galaxy F36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 217,
    discount: 5,
    isHot: true,
  },
  {
    id: 64,
    name: "Galaxy S25",
    brand: "Samsung",
    brandId: "samsung",
    price: 18068045,
    originalPrice: 21770000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-sm-s931.jpg",
    description:
      "Galaxy S25 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4000mAh.",
    rating: 5,
    reviews: 271,
    discount: 17,
    isHot: false,
  },
  {
    id: 65,
    name: "Galaxy F56",
    brand: "Samsung",
    brandId: "samsung",
    price: 8325720,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f56-5g.jpg",
    description:
      "Galaxy F56 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 19,
    discount: 28,
    isHot: false,
  },
  {
    id: 70,
    name: "Galaxy Z Flip6",
    brand: "Samsung",
    brandId: "samsung",
    price: 19377034,
    originalPrice: 25500000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
    description:
      "Galaxy Z Flip6 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4000mAh.",
    rating: 5,
    reviews: 254,
    discount: 24,
    isHot: true,
  },
  {
    id: 71,
    name: "Galaxy M55",
    brand: "Samsung",
    brandId: "samsung",
    price: 8464482,
    originalPrice: 10710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55.jpg",
    description:
      "Galaxy M55 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 5,
    reviews: 235,
    discount: 21,
    isHot: false,
  },
  {
    id: 72,
    name: "Galaxy M35",
    brand: "Samsung",
    brandId: "samsung",
    price: 6136364,
    originalPrice: 6970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m35-.jpg",
    description:
      "Galaxy M35 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 6000mAh.",
    rating: 4.9,
    reviews: 111,
    discount: 12,
    isHot: false,
  },
  {
    id: 74,
    name: "Galaxy M15",
    brand: "Samsung",
    brandId: "samsung",
    price: 4525799,
    originalPrice: 5590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m15.jpg",
    description:
      "Galaxy M15 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.0,
    reviews: 291,
    discount: 19,
    isHot: true,
  },

  {
    id: 76,
    name: "Galaxy S25 Edge",
    brand: "Samsung",
    brandId: "samsung",
    price: 22762210,
    originalPrice: 28810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-edge.jpg",
    description:
      "Galaxy S25 Edge là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 3900mAh.",
    rating: 4.7,
    reviews: 29,
    discount: 21,
    isHot: true,
  },
  {
    id: 77,
    name: "Galaxy XCover7 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 16512369,
    originalPrice: 19200000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover7-pro-1.jpg",
    description:
      "Galaxy XCover7 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 4350mAh.",
    rating: 4.7,
    reviews: 299,
    discount: 14,
    isHot: true,
  },
  {
    id: 78,
    name: "Galaxy S25+",
    brand: "Samsung",
    brandId: "samsung",
    price: 23435051,
    originalPrice: 28930000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus-sm-s936.jpg",
    description:
      "Galaxy S25+ là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4900mAh.",
    rating: 5,
    reviews: 100,
    discount: 19,
    isHot: true,
  },
  {
    id: 79,
    name: "Galaxy S24 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 12334091,
    originalPrice: 17130000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-fe-r1.jpg",
    description:
      "Galaxy S24 FE là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4700mAh.",
    rating: 4.3,
    reviews: 408,
    discount: 28,
    isHot: false,
  },
  {
    id: 80,
    name: "Galaxy A16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3551998,
    originalPrice: 4440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-lte.jpg",
    description:
      "Galaxy A16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 53,
    discount: 20,
    isHot: true,
  },
  {
    id: 82,
    name: "Galaxy Z Fold7",
    brand: "Samsung",
    brandId: "samsung",
    price: 43711571,
    originalPrice: 51430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold7.jpg",
    description:
      "Galaxy Z Fold7 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 5,
    reviews: 458,
    discount: 15,
    isHot: false,
  },
  {
    id: 83,
    name: "Galaxy M56",
    brand: "Samsung",
    brandId: "samsung",
    price: 8162828,
    originalPrice: 8970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m56-5g.jpg",
    description:
      "Galaxy M56 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 5,
    reviews: 380,
    discount: 9,
    isHot: true,
  },
  {
    id: 84,
    name: "Galaxy F14 4G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3083600,
    originalPrice: 4410000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f14-4g.jpg",
    description:
      "Galaxy F14 4G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 331,
    discount: 30,
    isHot: true,
  },
  {
    id: 85,
    name: "Galaxy F05",
    brand: "Samsung",
    brandId: "samsung",
    price: 1900840,
    originalPrice: 2160000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f05.jpg",
    description:
      "Galaxy F05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 448,
    discount: 12,
    isHot: false,
  },
  {
    id: 86,
    name: "Galaxy A35",
    brand: "Samsung",
    brandId: "samsung",
    price: 7308132,
    originalPrice: 7770000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg",
    description:
      "Galaxy A35 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 151,
    discount: 6,
    isHot: false,
  },
  {
    id: 87,
    name: "Galaxy A55",
    brand: "Samsung",
    brandId: "samsung",
    price: 10416092,
    originalPrice: 11570000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
    description:
      "Galaxy A55 là điện thoại cao cấp nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 86,
    discount: 10,
    isHot: true,
  },
  {
    id: 88,
    name: "Galaxy Z Fold6",
    brand: "Samsung",
    brandId: "samsung",
    price: 23976531,
    originalPrice: 25510000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg",
    description:
      "Galaxy Z Fold6 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.1,
    reviews: 328,
    discount: 6,
    isHot: true,
  },
  {
    id: 91,
    name: "Galaxy F06 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3031724,
    originalPrice: 3330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f06-5g.jpg",
    description:
      "Galaxy F06 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 66,
    discount: 9,
    isHot: false,
  },
  {
    id: 92,
    name: "Galaxy A06",
    brand: "Samsung",
    brandId: "samsung",
    price: 2774931,
    originalPrice: 3600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-1.jpg",
    description:
      "Galaxy A06 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 324,
    discount: 23,
    isHot: true,
  },
  {
    id: 93,
    name: "Galaxy A16 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4307480,
    originalPrice: 5670000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-5g.jpg",
    description:
      "Galaxy A16 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 210,
    discount: 24,
    isHot: true,
  },
  {
    id: 94,
    name: "Galaxy F55",
    brand: "Samsung",
    brandId: "samsung",
    price: 5166088,
    originalPrice: 6220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f55.jpg",
    description:
      "Galaxy F55 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 20,
    discount: 17,
    isHot: false,
  },
  {
    id: 95,
    name: "Galaxy M55s",
    brand: "Samsung",
    brandId: "samsung",
    price: 5171336,
    originalPrice: 6230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55s.jpg",
    description:
      "Galaxy M55s là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 73,
    discount: 17,
    isHot: true,
  },
  {
    id: 96,
    name: "Galaxy M16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3352418,
    originalPrice: 4470000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m16-5g-.jpg",
    description:
      "Galaxy M16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 429,
    discount: 25,
    isHot: false,
  },
  {
    id: 97,
    name: "Galaxy M05",
    brand: "Samsung",
    brandId: "samsung",
    price: 1894718,
    originalPrice: 2080000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m05.jpg",
    description:
      "Galaxy M05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 438,
    discount: 9,
    isHot: false,
  },
  {
    id: 98,
    name: "Galaxy Z Flip7 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 28878839,
    originalPrice: 34790000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip7-fe-.jpg",
    description:
      "Galaxy Z Flip7 FE là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 5,
    reviews: 89,
    discount: 17,
    isHot: false,
  },
  {
    id: 99,
    name: "Galaxy A06 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3060878,
    originalPrice: 3980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-5g.jpg",
    description:
      "Galaxy A06 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 351,
    discount: 23,
    isHot: true,
  },
  {
    id: 100,
    name: "Galaxy Z Fold Special",
    brand: "Samsung",
    brandId: "samsung",
    price: 57663320,
    originalPrice: 64070000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold-special-edition.jpg",
    description:
      "Galaxy Z Fold Special là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 16GB và pin 4400mAh.",
    rating: 4.8,
    reviews: 89,
    discount: 10,
    isHot: true,
  },
  {
    id: 101,
    name: "Galaxy A36",
    brand: "Samsung",
    brandId: "samsung",
    price: 6953209,
    originalPrice: 9520000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a36.jpg",
    description:
      "Galaxy A36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 157,
    discount: 27,
    isHot: false,
  },
  {
    id: 103,
    name: "Galaxy A15",
    brand: "Samsung",
    brandId: "samsung",
    price: 4902924,
    originalPrice: 5840000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15-lte-.jpg",
    description:
      "Galaxy A15 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 373,
    discount: 16,
    isHot: false,
  },
  {
    id: 104,
    name: "Galaxy S24",
    brand: "Samsung",
    brandId: "samsung",
    price: 13321152,
    originalPrice: 15670000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg",
    description:
      "Galaxy S24 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 4.9,
    reviews: 167,
    discount: 15,
    isHot: true,
  },
  {
    id: 107,
    name: "Galaxy A34",
    brand: "Samsung",
    brandId: "samsung",
    price: 5735496,
    originalPrice: 6440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a34.jpg",
    description:
      "Galaxy A34 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 447,
    discount: 11,
    isHot: false,
  },
  {
    id: 108,
    name: "Galaxy A14",
    brand: "Samsung",
    brandId: "samsung",
    price: 3778643,
    originalPrice: 4150000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a14-4g.jpg",
    description:
      "Galaxy A14 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 182,
    discount: 9,
    isHot: true,
  },
  {
    id: 109,
    name: "Galaxy M34 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7060000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m34-5g.jpg",
    description:
      "Galaxy M34 5G là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 476,
    discount: 17,
    isHot: true,
  },
  {
    id: 111,
    name: "Galaxy A14 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4594255,
    originalPrice: 6560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a14-5g.jpg",
    description:
      "Galaxy A14 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 24,
    discount: 30,
    isHot: false,
  },
  {
    id: 112,
    name: "Galaxy M54",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m54-5g.jpg",
    description:
      "Galaxy M54 là điện thoại tầm trung nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 211,
    discount: 24,
    isHot: true,
  },
  {
    id: 114,
    name: "Galaxy S23 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 16016218,
    originalPrice: 17800000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-ultra-5g.jpg",
    description:
      "Galaxy S23 Ultra là điện thoại cao cấp nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 139,
    discount: 10,
    isHot: false,
  },
  {
    id: 115,
    name: "Galaxy F14",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 5710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f14.jpg",
    description:
      "Galaxy F14 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 293,
    discount: 19,
    isHot: false,
  },
  {
    id: 116,
    name: "Galaxy A23 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4370694,
    originalPrice: 4600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23-5g.jpg",
    description:
      "Galaxy A23 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 255,
    discount: 5,
    isHot: true,
  },
  {
    id: 117,
    name: "Galaxy A04",
    brand: "Samsung",
    brandId: "samsung",
    price: 2288589,
    originalPrice: 2690000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04.jpg",
    description:
      "Galaxy A04 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 5,
    reviews: 390,
    discount: 15,
    isHot: true,
  },
  {
    id: 118,
    name: "Galaxy Z Flip4",
    brand: "Samsung",
    brandId: "samsung",
    price: 9374144,
    originalPrice: 12840000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip4-5g.jpg",
    description:
      "Galaxy Z Flip4 là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 5,
    reviews: 98,
    discount: 27,
    isHot: true,
  },
  {
    id: 119,
    name: "Galaxy S23+",
    brand: "Samsung",
    brandId: "samsung",
    price: 12519416,
    originalPrice: 13180000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-plus-5g.jpg",
    description:
      "Galaxy S23+ là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4700mAh.",
    rating: 5,
    reviews: 115,
    discount: 5,
    isHot: true,
  },
  {
    id: 120,
    name: "Galaxy Z Fold4",
    brand: "Samsung",
    brandId: "samsung",
    price: 15784640,
    originalPrice: 17350000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold4.jpg",
    description:
      "Galaxy Z Fold4 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.8,
    reviews: 298,
    discount: 9,
    isHot: true,
  },
  {
    id: 122,
    name: "Galaxy M14 4G",
    brand: "Samsung",
    brandId: "samsung",
    price: 2332028,
    originalPrice: 3070000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m14-4g.jpg",
    description:
      "Galaxy M14 4G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 436,
    discount: 24,
    isHot: true,
  },
  {
    id: 123,
    name: "Galaxy Z Fold5",
    brand: "Samsung",
    brandId: "samsung",
    price: 23073345,
    originalPrice: 24550000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold5-5g.jpg",
    description:
      "Galaxy Z Fold5 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.7,
    reviews: 303,
    discount: 6,
    isHot: true,
  },
  {
    id: 124,
    name: "Galaxy S23 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 11738956,
    originalPrice: 16530000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-fe.jpg",
    description:
      "Galaxy S23 FE là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 5,
    reviews: 307,
    discount: 29,
    isHot: false,
  },
  {
    id: 125,
    name: "Galaxy M14",
    brand: "Samsung",
    brandId: "samsung",
    price: 6167200,
    originalPrice: 7610000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m14-5g-sm-m146.jpg",
    description:
      "Galaxy M14 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 384,
    discount: 19,
    isHot: true,
  },
  {
    id: 126,
    name: "Galaxy F54",
    brand: "Samsung",
    brandId: "samsung",
    price: 10484240,
    originalPrice: 13980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f54-5g.jpg",
    description:
      "Galaxy F54 là điện thoại cao cấp nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 6000mAh.",
    rating: 4.3,
    reviews: 193,
    discount: 25,
    isHot: false,
  },
  {
    id: 127,
    name: "Galaxy Z Flip5",
    brand: "Samsung",
    brandId: "samsung",
    price: 16581442,
    originalPrice: 18630000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip5-5g.jpg",
    description:
      "Galaxy Z Flip5 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 5,
    reviews: 215,
    discount: 11,
    isHot: false,
  },
  {
    id: 129,
    name: "Galaxy F15",
    brand: "Samsung",
    brandId: "samsung",
    price: 3789728,
    originalPrice: 5050000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f15-5g.jpg",
    description:
      "Galaxy F15 là điện thoại giá rẻ nổi bật với thời lượng pin khủng, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 257,
    discount: 25,
    isHot: true,
  },
  {
    id: 130,
    name: "Galaxy A54",
    brand: "Samsung",
    brandId: "samsung",
    price: 5816286,
    originalPrice: 7090000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a54.jpg",
    description:
      "Galaxy A54 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 330,
    discount: 18,
    isHot: false,
  },
  {
    id: 131,
    name: "Galaxy A04s",
    brand: "Samsung",
    brandId: "samsung",
    price: 3188442,
    originalPrice: 3430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04s.jpg",
    description:
      "Galaxy A04s là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 55,
    discount: 7,
    isHot: false,
  },
  {
    id: 133,
    name: "Galaxy A05",
    brand: "Samsung",
    brandId: "samsung",
    price: 2291232,
    originalPrice: 2980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a05.jpg",
    description:
      "Galaxy A05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 218,
    discount: 23,
    isHot: true,
  },
  {
    id: 134,
    name: "Galaxy A25",
    brand: "Samsung",
    brandId: "samsung",
    price: 6760176,
    originalPrice: 8240000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a25.jpg",
    description:
      "Galaxy A25 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 96,
    discount: 18,
    isHot: true,
  },
  {
    id: 135,
    name: "Galaxy XCover7",
    brand: "Samsung",
    brandId: "samsung",
    price: 7215624,
    originalPrice: 10310000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover7.jpg",
    description:
      "Galaxy XCover7 là điện thoại tầm trung nổi bật với camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4050mAh.",
    rating: 5,
    reviews: 144,
    discount: 30,
    isHot: true,
  },
  {
    id: 141,
    name: "Galaxy A15 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5241811,
    originalPrice: 5890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15-5g-new.jpg",
    description:
      "Galaxy A15 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 312,
    discount: 11,
    isHot: true,
  },
  {
    id: 142,
    name: "Galaxy M04",
    brand: "Samsung",
    brandId: "samsung",
    price: 3083600,
    originalPrice: 4340000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m04-.jpg",
    description:
      "Galaxy M04 là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 185,
    discount: 29,
    isHot: false,
  },
  {
    id: 143,
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 21196974,
    originalPrice: 27530000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-stylus.jpg",
    description:
      "Galaxy S24 Ultra là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 5,
    reviews: 500,
    discount: 23,
    isHot: false,
  },
  {
    id: 144,
    name: "Galaxy S23",
    brand: "Samsung",
    brandId: "samsung",
    price: 10792600,
    originalPrice: 11990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-5g.jpg",
    description:
      "Galaxy S23 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 3900mAh.",
    rating: 5,
    reviews: 88,
    discount: 10,
    isHot: true,
  },
  {
    id: 145,
    name: "Galaxy A04e",
    brand: "Samsung",
    brandId: "samsung",
    price: 3160056,
    originalPrice: 3590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04e.jpg",
    description:
      "Galaxy A04e là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 210,
    discount: 12,
    isHot: false,
  },
  {
    id: 146,
    name: "Galaxy A05s",
    brand: "Samsung",
    brandId: "samsung",
    price: 3310552,
    originalPrice: 3480000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a05s.jpg",
    description:
      "Galaxy A05s là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 499,
    discount: 5,
    isHot: true,
  },
  {
    id: 147,
    name: "Galaxy S24+",
    brand: "Samsung",
    brandId: "samsung",
    price: 18408783,
    originalPrice: 21920000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-plus-5g-sm-s926.jpg",
    description:
      "Galaxy S24+ là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4900mAh.",
    rating: 5,
    reviews: 278,
    discount: 16,
    isHot: true,
  },
  {
    id: 148,
    name: "Galaxy S20 FE 2022",
    brand: "Samsung",
    brandId: "samsung",
    price: 16034720,
    originalPrice: 22580000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-fe-5g.jpg",
    description:
      "Galaxy S20 FE 2022 là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4500mAh.",
    rating: 4.8,
    reviews: 58,
    discount: 29,
    isHot: false,
  },
  {
    id: 149,
    name: "Galaxy A13 (SM-A137)",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 7710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13-a137.jpg",
    description:
      "Galaxy A13 (SM-A137) là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 23,
    discount: 28,
    isHot: false,
  },
  {
    id: 150,
    name: "Galaxy S22 Ultra 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 10083372,
    originalPrice: 10730000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-ultra-5g.jpg",
    description:
      "Galaxy S22 Ultra 5G là điện thoại cao cấp nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 61,
    discount: 6,
    isHot: false,
  },
  {
    id: 151,
    name: "Galaxy S22+ 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8603244,
    originalPrice: 12120000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-plus-5g.jpg",
    description:
      "Galaxy S22+ 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 4.0,
    reviews: 443,
    discount: 29,
    isHot: true,
  },
  {
    id: 152,
    name: "Galaxy A23",
    brand: "Samsung",
    brandId: "samsung",
    price: 6122048,
    originalPrice: 7120000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23.jpg",
    description:
      "Galaxy A23 là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 52,
    discount: 14,
    isHot: true,
  },
  {
    id: 153,
    name: "Galaxy M22",
    brand: "Samsung",
    brandId: "samsung",
    price: 7092280,
    originalPrice: 8760000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m22-.jpg",
    description:
      "Galaxy M22 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 373,
    discount: 19,
    isHot: true,
  },
  {
    id: 154,
    name: "Galaxy A12 (India)",
    brand: "Samsung",
    brandId: "samsung",
    price: 4933760,
    originalPrice: 5940000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-sm-a125.jpg",
    description:
      "Galaxy A12 (India) là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 193,
    discount: 17,
    isHot: true,
  },
  {
    id: 156,
    name: "Galaxy F52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017360,
    originalPrice: 9110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f52-5g.jpg",
    description:
      "Galaxy F52 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 4.2,
    reviews: 357,
    discount: 12,
    isHot: false,
  },
  {
    id: 157,
    name: "Galaxy A03",
    brand: "Samsung",
    brandId: "samsung",
    price: 4100879,
    originalPrice: 5330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03.jpg",
    description:
      "Galaxy A03 là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 263,
    discount: 23,
    isHot: false,
  },
  {
    id: 163,
    name: "Galaxy A13 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3946082,
    originalPrice: 4340000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13-5g-.jpg",
    description:
      "Galaxy A13 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 107,
    discount: 9,
    isHot: false,
  },
  {
    id: 164,
    name: "Galaxy A03s",
    brand: "Samsung",
    brandId: "samsung",
    price: 1817184,
    originalPrice: 2110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03s.jpg",
    description:
      "Galaxy A03s là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 5,
    reviews: 466,
    discount: 14,
    isHot: true,
  },
  {
    id: 165,
    name: "Galaxy M52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 9250800,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32-5g-.jpg",
    description:
      "Galaxy M52 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 266,
    discount: 20,
    isHot: false,
  },
  {
    id: 166,
    name: "Galaxy M13 (India)",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 6010000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13-4g-india.jpg",
    description:
      "Galaxy M13 (India) là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 260,
    discount: 23,
    isHot: false,
  },
  {
    id: 168,
    name: "Galaxy A22 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3414470,
    originalPrice: 4740000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a22-5g.jpg",
    description:
      "Galaxy A22 5G là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 230,
    discount: 28,
    isHot: false,
  },
  {
    id: 169,
    name: "Galaxy A13",
    brand: "Samsung",
    brandId: "samsung",
    price: 3511912,
    originalPrice: 3900000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13.jpg",
    description:
      "Galaxy A13 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 407,
    discount: 10,
    isHot: false,
  },
  {
    id: 170,
    name: "Galaxy F23",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m23.jpg",
    description:
      "Galaxy F23 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 391,
    discount: 19,
    isHot: false,
  },
  {
    id: 171,
    name: "Galaxy M32 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6783920,
    originalPrice: 7140000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32-5g-new.jpg",
    description:
      "Galaxy M32 5G là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 110,
    discount: 5,
    isHot: false,
  },
  {
    id: 172,
    name: "Galaxy M53",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017051,
    originalPrice: 8440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m53-5g.jpg",
    description:
      "Galaxy M53 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 209,
    discount: 5,
    isHot: true,
  },
  {
    id: 173,
    name: "Galaxy A12 Nacho",
    brand: "Samsung",
    brandId: "samsung",
    price: 4008680,
    originalPrice: 4890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-nacho.jpg",
    description:
      "Galaxy A12 Nacho là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 269,
    discount: 18,
    isHot: false,
  },
  {
    id: 175,
    name: "Galaxy A53 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6387677,
    originalPrice: 7020000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a53-5g-.jpg",
    description:
      "Galaxy A53 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 482,
    discount: 9,
    isHot: true,
  },
  {
    id: 176,
    name: "Galaxy S22 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7061444,
    originalPrice: 8410000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-5g.jpg",
    description:
      "Galaxy S22 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 4.0,
    reviews: 253,
    discount: 16,
    isHot: false,
  },
  {
    id: 177,
    name: "Galaxy A52s 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017360,
    originalPrice: 8620000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a52s-5g.jpg",
    description:
      "Galaxy A52s 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4500mAh.",
    rating: 5,
    reviews: 472,
    discount: 7,
    isHot: true,
  },
  {
    id: 178,
    name: "Galaxy M13",
    brand: "Samsung",
    brandId: "samsung",
    price: 3965509,
    originalPrice: 5510000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13.jpg",
    description:
      "Galaxy M13 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 340,
    discount: 28,
    isHot: true,
  },
  {
    id: 179,
    name: "Galaxy S21 FE 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6475560,
    originalPrice: 7800000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg",
    description:
      "Galaxy S21 FE 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4500mAh.",
    rating: 5,
    reviews: 134,
    discount: 17,
    isHot: true,
  },
  {
    id: 180,
    name: "Galaxy A22",
    brand: "Samsung",
    brandId: "samsung",
    price: 6136672,
    originalPrice: 8640000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a22.jpg",
    description:
      "Galaxy A22 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 25,
    discount: 29,
    isHot: true,
  },
  {
    id: 181,
    name: "Galaxy M42 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6783920,
    originalPrice: 7290000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m42.jpg",
    description:
      "Galaxy M42 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 249,
    discount: 7,
    isHot: true,
  },
  {
    id: 182,
    name: "Galaxy F22",
    brand: "Samsung",
    brandId: "samsung",
    price: 5242120,
    originalPrice: 5760000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f22.jpg",
    description:
      "Galaxy F22 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.6,
    reviews: 243,
    discount: 9,
    isHot: true,
  },
  {
    id: 183,
    name: "Galaxy F13",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 5080000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f13.jpg",
    description:
      "Galaxy F13 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.7,
    reviews: 346,
    discount: 9,
    isHot: false,
  },
  {
    id: 184,
    name: "Galaxy M32",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 6850000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32.jpg",
    description:
      "Galaxy M32 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 219,
    discount: 19,
    isHot: true,
  },
  {
    id: 185,
    name: "Galaxy M21 2021",
    brand: "Samsung",
    brandId: "samsung",
    price: 4008680,
    originalPrice: 4660000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m21-2021.jpg",
    description:
      "Galaxy M21 2021 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.4,
    reviews: 75,
    discount: 14,
    isHot: true,
  },
  {
    id: 186,
    name: "Galaxy M12",
    brand: "Samsung",
    brandId: "samsung",
    price: 5242120,
    originalPrice: 6100000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m12.jpg",
    description:
      "Galaxy M12 là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 5,
    reviews: 22,
    discount: 14,
    isHot: false,
  },
  {
    id: 187,
    name: "Galaxy A33 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5116309,
    originalPrice: 7110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a33-5g.jpg",
    description:
      "Galaxy A33 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 450,
    discount: 28,
    isHot: true,
  },
  {
    id: 188,
    name: "Galaxy Z Flip3 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8788260,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip3-5g.jpg",
    description:
      "Galaxy Z Flip3 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3300mAh.",
    rating: 4.6,
    reviews: 342,
    discount: 24,
    isHot: false,
  },
  {
    id: 189,
    name: "Galaxy A03 Core",
    brand: "Samsung",
    brandId: "samsung",
    price: 1816920,
    originalPrice: 2000000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03-core.jpg",
    description:
      "Galaxy A03 Core là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 94,
    discount: 9,
    isHot: true,
  },
  {
    id: 190,
    name: "Galaxy Z Fold3 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 16959800,
    originalPrice: 23890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold3-5g.jpg",
    description:
      "Galaxy Z Fold3 5G là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 5,
    reviews: 486,
    discount: 29,
    isHot: true,
  },
  {
    id: 191,
    name: "Galaxy F42 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7400640,
    originalPrice: 10280000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f42-5g.jpg",
    description:
      "Galaxy F42 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 233,
    discount: 28,
    isHot: false,
  },
  {
    id: 192,
    name: "Galaxy M23",
    brand: "Samsung",
    brandId: "samsung",
    price: 6463842,
    originalPrice: 7600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m23.jpg",
    description:
      "Galaxy M23 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 241,
    discount: 15,
    isHot: true,
  },
  {
    id: 193,
    name: "Galaxy M33",
    brand: "Samsung",
    brandId: "samsung",
    price: 8633771,
    originalPrice: 12330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m33.jpg",
    description:
      "Galaxy M33 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 215,
    discount: 30,
    isHot: false,
  },
  {
    id: 194,
    name: "Galaxy M13 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 6610000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13-5g.jpg",
    description:
      "Galaxy M13 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 312,
    discount: 16,
    isHot: true,
  },
  {
    id: 195,
    name: "Galaxy A73 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 18501600,
    originalPrice: 25000000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a73-5g.jpg",
    description:
      "Galaxy A73 5G là điện thoại cao cấp nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 331,
    discount: 26,
    isHot: true,
  },
  {
    id: 196,
    name: "Galaxy XCover6 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 8940898,
    originalPrice: 10050000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover6-pro-r.jpg",
    description:
      "Galaxy XCover6 Pro là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 4050mAh.",
    rating: 4.5,
    reviews: 29,
    discount: 11,
    isHot: true,
  },
  {
    id: 197,
    name: "Galaxy A52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7839127,
    originalPrice: 10740000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a52-5g.jpg",
    description:
      "Galaxy A52 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4500mAh.",
    rating: 4.3,
    reviews: 21,
    discount: 27,
    isHot: true,
  },
  {
    id: 198,
    name: "Xperia 1 VI",
    brand: "Sony",
    brandId: "sony",
    price: 46099820,
    originalPrice: 54880000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi-red.jpg",
    description:
      "Xperia 1 VI là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 206,
    discount: 16,
    isHot: true,
  },
  {
    id: 199,
    name: "Xperia 5 IV",
    brand: "Sony",
    brandId: "sony",
    price: 26309664,
    originalPrice: 27990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-iv-ofic.jpg",
    description:
      "Xperia 5 IV là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 361,
    discount: 6,
    isHot: true,
  },
  {
    id: 200,
    name: "Xperia 5 V",
    brand: "Sony",
    brandId: "sony",
    price: 33735889,
    originalPrice: 36670000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-v-new.jpg",
    description:
      "Xperia 5 V là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 453,
    discount: 8,
    isHot: true,
  },
  {
    id: 201,
    name: "Xperia XA1 Ultra",
    brand: "Sony",
    brandId: "sony",
    price: 7709000,
    originalPrice: 10710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-xa1-ultra-2017.jpg",
    description:
      "Xperia XA1 Ultra là điện thoại tầm trung có thiết kế hiện đại, phù hợp cho nhu cầu hàng ngày. Máy được trang bị RAM 4GB và pin 2700mAh.",
    rating: 4.3,
    reviews: 372,
    discount: 28,
    isHot: false,
  },
  {
    id: 202,
    name: "Xperia Pro-I",
    brand: "Sony",
    brandId: "sony",
    price: 28677480,
    originalPrice: 32220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-pro-i.jpg",
    description:
      "Xperia Pro-I là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 4500mAh.",
    rating: 5,
    reviews: 52,
    discount: 11,
    isHot: false,
  },
  {
    id: 203,
    name: "Xperia 1 II",
    brand: "Sony",
    brandId: "sony",
    price: 21585200,
    originalPrice: 26980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-II-o.jpg",
    description:
      "Xperia 1 II là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 5,
    reviews: 491,
    discount: 20,
    isHot: false,
  },
];
