import { Product } from "react-sigma-chatbox";

export const productList: Product[] = [
  {
    id: 1,
    name: "iPad Air 13 (2025)",
    brand: "Apple",
    brandId: "apple",
    price: 29294200,
    originalPrice: 41260000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-13-2025.jpg",
    description:
      "iPad Air 13 (2025) là mẫu tablet màn hình lớn hướng tới người dùng làm việc và sáng tạo. Chip Apple M3 mang lại hiệu năng mạnh cho chỉnh sửa ảnh, video và đa nhiệm, trong khi màn hình 13 inch hiển thị rộng rãi, sắc nét, phù hợp thay thế laptop cơ bản.",
    rating: 5,
    reviews: 290,
    discount: 29,
    isHot: true,
  },
  {
    id: 2,
    name: "Watch Series 10 Aluminum",
    brand: "Apple",
    brandId: "apple",
    price: 10453404,
    originalPrice: 11750000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series10-alumin.jpg",
    description:
      "Apple Watch Series 10 Aluminum tập trung vào theo dõi sức khỏe và luyện tập hằng ngày với màn hình OLED sáng, nhẹ và thoải mái đeo lâu. Chip S10 cải thiện độ mượt, phù hợp người dùng iPhone muốn một chiếc smartwatch cân bằng giữa tính năng và giá.",
    rating: 5,
    reviews: 265,
    discount: 11,
    isHot: true,
  },
  {
    id: 3,
    name: "iPad Pro 11 (2024)",
    brand: "Apple",
    brandId: "apple",
    price: 37003200,
    originalPrice: 39370000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2024.jpg",
    description:
      "iPad Pro 11 (2024) là tablet cao cấp nhất của Apple với màn hình OLED 120Hz và chip M4 cực mạnh. Máy đáp ứng tốt các tác vụ chuyên nghiệp như dựng video, vẽ kỹ thuật số, lập trình và làm việc cường độ cao trong thân hình gọn nhẹ.",
    rating: 4.6,
    reviews: 78,
    discount: 6,
    isHot: true,
  },
  {
    id: 4,
    name: "Watch Series 9 Aluminum",
    brand: "Apple",
    brandId: "apple",
    price: 10484240,
    originalPrice: 11650000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series9-aluminum.jpg",
    description:
      "Apple Watch Series 9 Aluminum mang lại trải nghiệm mượt mà, đo sức khỏe chính xác và tích hợp sâu hệ sinh thái Apple. Phù hợp người dùng phổ thông cần một smartwatch ổn định, dễ dùng và bền bỉ.",
    rating: 4.1,
    reviews: 249,
    discount: 10,
    isHot: false,
  },
  {
    id: 5,
    name: "Watch Ultra 2",
    brand: "Apple",
    brandId: "apple",
    price: 18809651,
    originalPrice: 24430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra2-black.jpg",
    description:
      "Apple Watch Ultra 2 được thiết kế cho vận động mạnh và môi trường khắc nghiệt với khung titanium, pin lớn và độ bền cao. GPS chính xác và nhiều cảm biến hỗ trợ thể thao chuyên sâu, đặc biệt là outdoor.",
    rating: 5,
    reviews: 75,
    discount: 23,
    isHot: false,
  },
  {
    id: 6,
    name: "iPhone 15",
    brand: "Apple",
    brandId: "apple",
    price: 16713112,
    originalPrice: 17970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
    description:
      "iPhone 15 là mẫu iPhone cân bằng giữa hiệu năng, camera và thiết kế. Camera 48MP cho chất lượng ảnh tốt trong nhiều điều kiện, chip A16 đủ mạnh cho mọi tác vụ hàng ngày và chơi game phổ biến.",
    rating: 4.1,
    reviews: 65,
    discount: 7,
    isHot: true,
  },
  {
    id: 7,
    name: "Watch SE (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 5550171,
    originalPrice: 7930000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-8se-2022.jpg",
    description:
      "Apple Watch SE (2022) là lựa chọn smartwatch giá tốt cho người mới bắt đầu. Máy đáp ứng các tính năng cơ bản như theo dõi sức khỏe, thông báo và luyện tập mà không quá phức tạp.",
    rating: 4.4,
    reviews: 19,
    discount: 30,
    isHot: false,
  },
  {
    id: 8,
    name: "Watch Ultra",
    brand: "Apple",
    brandId: "apple",
    price: 16959800,
    originalPrice: 18840000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra.jpg",
    description:
      "Apple Watch Ultra là smartwatch cao cấp dành cho người yêu thể thao và hoạt động ngoài trời. Thiết kế hầm hố, pin tốt và độ bền cao giúp máy hoạt động ổn định trong điều kiện khắc nghiệt.",
    rating: 5,
    reviews: 128,
    discount: 10,
    isHot: false,
  },
  {
    id: 9,
    name: "iPad Air (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 16959800,
    originalPrice: 22610000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-2022-new.jpg",
    description:
      "iPad Air (2022) trang bị chip M1 mạnh mẽ trong thân máy mỏng nhẹ, phù hợp người dùng cần tablet hiệu năng cao cho học tập và làm việc nhưng không cần tới iPad Pro.",
    rating: 4.7,
    reviews: 393,
    discount: 25,
    isHot: true,
  },
  {
    id: 10,
    name: "iPhone SE (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 4471220,
    originalPrice: 5960000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg",
    description:
      "iPhone SE (2022) là mẫu iPhone nhỏ gọn với chip A15 mạnh mẽ, mang lại hiệu năng cao trong thiết kế truyền thống. Phù hợp người thích Touch ID và máy nhỏ dễ cầm.",
    rating: 4.8,
    reviews: 64,
    discount: 25,
    isHot: true,
  },
  {
    id: 11,
    name: "iPad (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 13259480,
    originalPrice: 16370000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-10-2022.jpg",
    description:
      "iPad (2022) là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 7606mAh.",
    rating: 4.1,
    reviews: 363,
    discount: 19,
    isHot: false,
  },
  {
    id: 12,
    name: "iPhone 12 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 10854272,
    originalPrice: 14100000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro--.jpg",
    description:
      "iPhone 12 Pro là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 2815mAh.",
    rating: 4.1,
    reviews: 116,
    discount: 23,
    isHot: false,
  },
  {
    id: 13,
    name: "iPhone 13 mini",
    brand: "Apple",
    brandId: "apple",
    price: 9124064,
    originalPrice: 12500000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-mini.jpg",
    description:
      "iPhone 13 mini là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2438mAh.",
    rating: 4.9,
    reviews: 51,
    discount: 27,
    isHot: true,
  },
  {
    id: 14,
    name: "iPhone 14 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 14368959,
    originalPrice: 19960000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-plus.jpg",
    description:
      "iPhone 14 Plus là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 4323mAh.",
    rating: 4.0,
    reviews: 456,
    discount: 28,
    isHot: false,
  },
  {
    id: 15,
    name: "Watch Series 8",
    brand: "Apple",
    brandId: "apple",
    price: 10175880,
    originalPrice: 10710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-8.jpg",
    description:
      "Watch Series 8 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 308mAh.",
    rating: 5,
    reviews: 298,
    discount: 5,
    isHot: true,
  },
  {
    id: 16,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 25593880,
    originalPrice: 33240000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
    description:
      "iPhone 15 Pro Max là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 4441mAh.",
    rating: 4.9,
    reviews: 370,
    discount: 23,
    isHot: false,
  },
  {
    id: 17,
    name: "iPad mini (2024)",
    brand: "Apple",
    brandId: "apple",
    price: 18501600,
    originalPrice: 26430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-2024.jpg",
    description:
      "iPad mini (2024) là điện thoại cao cấp nổi bật với pin cả ngày. Máy được trang bị RAM 8GB và pin 5078mAh.",
    rating: 4.1,
    reviews: 455,
    discount: 30,
    isHot: true,
  },
  {
    id: 18,
    name: "iPhone 16e",
    brand: "Apple",
    brandId: "apple",
    price: 17237324,
    originalPrice: 18140000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-4-2024.jpg",
    description:
      "iPhone 16e là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 3279mAh.",
    rating: 5,
    reviews: 63,
    discount: 5,
    isHot: true,
  },
  {
    id: 19,
    name: "iPhone 16 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 24535896,
    originalPrice: 27880000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg",
    description:
      "iPhone 16 Plus là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 4674mAh.",
    rating: 4.6,
    reviews: 399,
    discount: 12,
    isHot: true,
  },
  {
    id: 20,
    name: "iPhone 14",
    brand: "Apple",
    brandId: "apple",
    price: 11995204,
    originalPrice: 12630000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
    description:
      "iPhone 14 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 3279mAh.",
    rating: 5,
    reviews: 336,
    discount: 5,
    isHot: false,
  },
  {
    id: 21,
    name: "Watch Series 10",
    brand: "Apple",
    brandId: "apple",
    price: 24391276,
    originalPrice: 30880000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series10.jpg",
    description:
      "Watch Series 10 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 327mAh.",
    rating: 4.6,
    reviews: 306,
    discount: 21,
    isHot: false,
  },
  {
    id: 22,
    name: "iPhone 12 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 13073538,
    originalPrice: 15380000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro-max-.jpg",
    description:
      "iPhone 12 Pro Max là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 3687mAh.",
    rating: 4.4,
    reviews: 281,
    discount: 15,
    isHot: false,
  },
  {
    id: 23,
    name: "Watch Series 7",
    brand: "Apple",
    brandId: "apple",
    price: 9559160,
    originalPrice: 13090000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series-7-stainless-steel.jpg",
    description:
      "Watch Series 7 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 309mAh.",
    rating: 5,
    reviews: 355,
    discount: 27,
    isHot: false,
  },
  {
    id: 24,
    name: "iPhone 12",
    brand: "Apple",
    brandId: "apple",
    price: 7246460,
    originalPrice: 10210000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg",
    description:
      "iPhone 12 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2815mAh.",
    rating: 4.9,
    reviews: 465,
    discount: 29,
    isHot: false,
  },
  {
    id: 25,
    name: "iPhone 16",
    brand: "Apple",
    brandId: "apple",
    price: 21078872,
    originalPrice: 25400000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
    description:
      "iPhone 16 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 3561mAh.",
    rating: 4.6,
    reviews: 291,
    discount: 17,
    isHot: false,
  },
  {
    id: 26,
    name: "iPhone 16 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 27135680,
    originalPrice: 37170000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
    description:
      "iPhone 16 Pro là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3582mAh.",
    rating: 5,
    reviews: 244,
    discount: 27,
    isHot: true,
  },
  {
    id: 27,
    name: "iPhone 15 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 22171084,
    originalPrice: 27040000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg",
    description:
      "iPhone 15 Pro là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3274mAh.",
    rating: 4.5,
    reviews: 14,
    discount: 18,
    isHot: false,
  },
  {
    id: 28,
    name: "iPhone 15 Plus",
    brand: "Apple",
    brandId: "apple",
    price: 20503164,
    originalPrice: 24700000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-plus-.jpg",
    description:
      "iPhone 15 Plus là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 4383mAh.",
    rating: 4.6,
    reviews: 466,
    discount: 17,
    isHot: true,
  },
  {
    id: 29,
    name: "iPad Pro 11 (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 32377800,
    originalPrice: 42600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2022.jpg",
    description:
      "iPad Pro 11 (2022) là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 7538mAh.",
    rating: 4.8,
    reviews: 329,
    discount: 24,
    isHot: true,
  },
  {
    id: 30,
    name: "iPad Pro 11 (2021)",
    brand: "Apple",
    brandId: "apple",
    price: 26827320,
    originalPrice: 31560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2021.jpg",
    description:
      "iPad Pro 11 (2021) là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 7538mAh.",
    rating: 4.7,
    reviews: 189,
    discount: 15,
    isHot: true,
  },
  {
    id: 31,
    name: "Watch Series 7 Aluminum",
    brand: "Apple",
    brandId: "apple",
    price: 15418000,
    originalPrice: 17320000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series-7-aluminum.jpg",
    description:
      "Watch Series 7 Aluminum là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 309mAh.",
    rating: 4.8,
    reviews: 353,
    discount: 11,
    isHot: true,
  },
  {
    id: 32,
    name: "iPhone 13",
    brand: "Apple",
    brandId: "apple",
    price: 10422568,
    originalPrice: 13540000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
    description:
      "iPhone 13 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3240mAh.",
    rating: 4.1,
    reviews: 410,
    discount: 23,
    isHot: true,
  },
  {
    id: 33,
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 15078495,
    originalPrice: 16570000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro-max.jpg",
    description:
      "iPhone 13 Pro Max là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4352mAh.",
    rating: 5,
    reviews: 422,
    discount: 9,
    isHot: false,
  },
  {
    id: 34,
    name: "iPad Pro 13 (2024)",
    brand: "Apple",
    brandId: "apple",
    price: 47795800,
    originalPrice: 64590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-13-2024.jpg",
    description:
      "iPad Pro 13 (2024) là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 10290mAh.",
    rating: 4.8,
    reviews: 202,
    discount: 26,
    isHot: false,
  },
  {
    id: 35,
    name: "iPad Air 11 (2024)",
    brand: "Apple",
    brandId: "apple",
    price: 21585200,
    originalPrice: 22720000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2024.jpg",
    description:
      "iPad Air 11 (2024) là điện thoại flagship nổi bật với thời lượng pin khủng. Máy được trang bị RAM 8GB và pin 7606mAh.",
    rating: 4.6,
    reviews: 214,
    discount: 5,
    isHot: false,
  },
  {
    id: 36,
    name: "Watch Series 9",
    brand: "Apple",
    brandId: "apple",
    price: 19426680,
    originalPrice: 25560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series9.jpg",
    description:
      "Watch Series 9 là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 308mAh.",
    rating: 4.5,
    reviews: 128,
    discount: 24,
    isHot: false,
  },
  {
    id: 37,
    name: "iPad mini (2021)",
    brand: "Apple",
    brandId: "apple",
    price: 16959800,
    originalPrice: 20190000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-2021.jpg",
    description:
      "iPad mini (2021) là điện thoại cao cấp nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5078mAh.",
    rating: 5,
    reviews: 460,
    discount: 16,
    isHot: false,
  },
  {
    id: 38,
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 33765111,
    originalPrice: 35540000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
    description:
      "iPhone 16 Pro Max là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 4685mAh.",
    rating: 4.4,
    reviews: 465,
    discount: 5,
    isHot: false,
  },
  {
    id: 39,
    name: "iPhone 14 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 16928964,
    originalPrice: 17820000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg",
    description:
      "iPhone 14 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 3200mAh.",
    rating: 4.8,
    reviews: 475,
    discount: 5,
    isHot: true,
  },
  {
    id: 40,
    name: "iPad Pro 12.9 (2022)",
    brand: "Apple",
    brandId: "apple",
    price: 44712200,
    originalPrice: 56600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-129-2022.jpg",
    description:
      "iPad Pro 12.9 (2022) là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 10758mAh.",
    rating: 5,
    reviews: 231,
    discount: 21,
    isHot: true,
  },
  {
    id: 41,
    name: "iPad (2025)",
    brand: "Apple",
    brandId: "apple",
    price: 12334400,
    originalPrice: 15810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-11-inch-2025.jpg",
    description:
      "iPad (2025) là điện thoại cao cấp có thiết kế hiện đại, phù hợp cho nhu cầu hàng ngày. Máy được trang bị RAM 6GB và pin 2893mAh.",
    rating: 4.4,
    reviews: 173,
    discount: 22,
    isHot: false,
  },
  {
    id: 42,
    name: "iPhone 12 mini",
    brand: "Apple",
    brandId: "apple",
    price: 6166891,
    originalPrice: 7810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-mini.jpg",
    description:
      "iPhone 12 mini là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 2227mAh.",
    rating: 4.2,
    reviews: 147,
    discount: 21,
    isHot: false,
  },
  {
    id: 43,
    name: "iPad Air 11 (2025)",
    brand: "Apple",
    brandId: "apple",
    price: 21585200,
    originalPrice: 28030000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2025.jpg",
    description:
      "iPad Air 11 (2025) là điện thoại flagship nổi bật với thời lượng pin khủng. Máy được trang bị RAM 8GB và pin 7606mAh.",
    rating: 4.3,
    reviews: 207,
    discount: 23,
    isHot: false,
  },
  {
    id: 44,
    name: "iPhone 13 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 13814528,
    originalPrice: 16250000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
    description:
      "iPhone 13 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 3095mAh.",
    rating: 5,
    reviews: 498,
    discount: 15,
    isHot: false,
  },
  {
    id: 45,
    name: "Watch Series 8 Aluminum",
    brand: "Apple",
    brandId: "apple",
    price: 10484240,
    originalPrice: 11520000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-8-aluminum.jpg",
    description:
      "Watch Series 8 Aluminum là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 308mAh.",
    rating: 4.1,
    reviews: 260,
    discount: 9,
    isHot: false,
  },
  {
    id: 46,
    name: "iPad Pro 11 (2020)",
    brand: "Apple",
    brandId: "apple",
    price: 24668800,
    originalPrice: 33790000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2020.jpg",
    description:
      "iPad Pro 11 (2020) là điện thoại flagship nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 7538mAh.",
    rating: 4.4,
    reviews: 49,
    discount: 27,
    isHot: false,
  },
  {
    id: 47,
    name: "iPad Air (2020)",
    brand: "Apple",
    brandId: "apple",
    price: 19735040,
    originalPrice: 20770000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air4-2020.jpg",
    description:
      "iPad Air (2020) là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 7606mAh.",
    rating: 4.8,
    reviews: 189,
    discount: 5,
    isHot: true,
  },
  {
    id: 48,
    name: "Watch Series 6",
    brand: "Apple",
    brandId: "apple",
    price: 21893560,
    originalPrice: 27030000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-s6-steel.jpg",
    description:
      "Watch Series 6 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 3038mAh.",
    rating: 4.8,
    reviews: 313,
    discount: 19,
    isHot: true,
  },
  {
    id: 49,
    name: "Watch Series 6 Aluminum",
    brand: "Apple",
    brandId: "apple",
    price: 12951120,
    originalPrice: 15990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-s6.jpg",
    description:
      "Watch Series 6 Aluminum là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 3038mAh.",
    rating: 4.7,
    reviews: 170,
    discount: 19,
    isHot: true,
  },
  {
    id: 50,
    name: "Watch Edition Series 5",
    brand: "Apple",
    brandId: "apple",
    price: 26210600,
    originalPrice: 29450000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-edition-series-5.jpg",
    description:
      "Watch Edition Series 5 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 296mAh.",
    rating: 4.7,
    reviews: 159,
    discount: 11,
    isHot: true,
  },
  {
    id: 51,
    name: "iPhone 11 Pro",
    brand: "Apple",
    brandId: "apple",
    price: 7400640,
    originalPrice: 9870000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro-max-.jpg",
    description:
      "iPhone 11 Pro là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3046mAh.",
    rating: 4.3,
    reviews: 279,
    discount: 25,
    isHot: false,
  },
  {
    id: 52,
    name: "Watch Series 4",
    brand: "Apple",
    brandId: "apple",
    price: 21585200,
    originalPrice: 30400000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series-4-steel.jpg",
    description:
      "Watch Series 4 là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 1GB và pin 292mAh.",
    rating: 5,
    reviews: 347,
    discount: 29,
    isHot: true,
  },
  {
    id: 53,
    name: "iPhone 11 Pro Max",
    brand: "Apple",
    brandId: "apple",
    price: 9106179,
    originalPrice: 11980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro.jpg",
    description:
      "iPhone 11 Pro Max là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 3969mAh.",
    rating: 5,
    reviews: 190,
    discount: 24,
    isHot: true,
  },
  {
    id: 54,
    name: "iPad 10.2 (2020)",
    brand: "Apple",
    brandId: "apple",
    price: 11409320,
    originalPrice: 13110000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad8-102-inches-2020.jpg",
    description:
      "iPad 10.2 (2020) là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 3GB và pin 8827mAh.",
    rating: 4.2,
    reviews: 13,
    discount: 13,
    isHot: false,
  },
  {
    id: 55,
    name: "Galaxy Z Flip7",
    brand: "Samsung",
    brandId: "samsung",
    price: 28687964,
    originalPrice: 32230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip7.jpg",
    description:
      "Galaxy Z Flip7 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4300mAh.",
    rating: 5,
    reviews: 21,
    discount: 11,
    isHot: false,
  },
  {
    id: 56,
    name: "Galaxy M36",
    brand: "Samsung",
    brandId: "samsung",
    price: 5101658,
    originalPrice: 6990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m36.jpg",
    description:
      "Galaxy M36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 297,
    discount: 27,
    isHot: false,
  },
  {
    id: 57,
    name: "Galaxy Tab Active5 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 27752400,
    originalPrice: 33840000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-active5-pro.jpg",
    description:
      "Galaxy Tab Active5 Pro là điện thoại flagship nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 10100mAh.",
    rating: 4.5,
    reviews: 210,
    discount: 18,
    isHot: true,
  },
  {
    id: 58,
    name: "Galaxy A26",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 6300000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a26.jpg",
    description:
      "Galaxy A26 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 478,
    discount: 7,
    isHot: false,
  },
  {
    id: 59,
    name: "Galaxy M06",
    brand: "Samsung",
    brandId: "samsung",
    price: 2769338,
    originalPrice: 3180000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m06-5g.jpg",
    description:
      "Galaxy M06 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 453,
    discount: 13,
    isHot: true,
  },
  {
    id: 60,
    name: "Galaxy A56",
    brand: "Samsung",
    brandId: "samsung",
    price: 9096620,
    originalPrice: 12810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a56-.jpg",
    description:
      "Galaxy A56 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 329,
    discount: 29,
    isHot: false,
  },
  {
    id: 61,
    name: "Galaxy F16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3495273,
    originalPrice: 4920000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f16-5g.jpg",
    description:
      "Galaxy F16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 24,
    discount: 29,
    isHot: true,
  },
  {
    id: 62,
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 27721564,
    originalPrice: 29180000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-ultra-sm-s938.jpg",
    description:
      "Galaxy S25 Ultra là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 106,
    discount: 5,
    isHot: false,
  },
  {
    id: 63,
    name: "Galaxy F36",
    brand: "Samsung",
    brandId: "samsung",
    price: 4955888,
    originalPrice: 5220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f36.jpg",
    description:
      "Galaxy F36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 217,
    discount: 5,
    isHot: true,
  },
  {
    id: 64,
    name: "Galaxy S25",
    brand: "Samsung",
    brandId: "samsung",
    price: 18068045,
    originalPrice: 21770000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-sm-s931.jpg",
    description:
      "Galaxy S25 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4000mAh.",
    rating: 5,
    reviews: 271,
    discount: 17,
    isHot: false,
  },
  {
    id: 65,
    name: "Galaxy F56",
    brand: "Samsung",
    brandId: "samsung",
    price: 8325720,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f56-5g.jpg",
    description:
      "Galaxy F56 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 19,
    discount: 28,
    isHot: false,
  },
  {
    id: 66,
    name: "Galaxy Watch7",
    brand: "Samsung",
    brandId: "samsung",
    price: 5023184,
    originalPrice: 6790000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch7.jpg",
    description:
      "Galaxy Watch7 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 2GB và pin 425mAh.",
    rating: 4.3,
    reviews: 230,
    discount: 26,
    isHot: false,
  },
  {
    id: 67,
    name: "Galaxy Tab S10 FE+",
    brand: "Samsung",
    brandId: "samsung",
    price: 15537976,
    originalPrice: 20440000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s10-fe-plus.jpg",
    description:
      "Galaxy Tab S10 FE+ là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 8GB và pin 10090mAh.",
    rating: 5,
    reviews: 217,
    discount: 24,
    isHot: false,
  },
  {
    id: 68,
    name: "Galaxy Watch FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 4162551,
    originalPrice: 5140000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch-fe-r.jpg",
    description:
      "Galaxy Watch FE là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 5GB và pin 247mAh.",
    rating: 5,
    reviews: 313,
    discount: 19,
    isHot: false,
  },
  {
    id: 69,
    name: "Galaxy Tab S10 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 37003200,
    originalPrice: 51390000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s10-ultra.jpg",
    description:
      "Galaxy Tab S10 Ultra là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 11200mAh.",
    rating: 5,
    reviews: 257,
    discount: 28,
    isHot: true,
  },
  {
    id: 70,
    name: "Galaxy Z Flip6",
    brand: "Samsung",
    brandId: "samsung",
    price: 19377034,
    originalPrice: 25500000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip6.jpg",
    description:
      "Galaxy Z Flip6 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4000mAh.",
    rating: 5,
    reviews: 254,
    discount: 24,
    isHot: true,
  },
  {
    id: 71,
    name: "Galaxy M55",
    brand: "Samsung",
    brandId: "samsung",
    price: 8464482,
    originalPrice: 10710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55.jpg",
    description:
      "Galaxy M55 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 5,
    reviews: 235,
    discount: 21,
    isHot: false,
  },
  {
    id: 72,
    name: "Galaxy M35",
    brand: "Samsung",
    brandId: "samsung",
    price: 6136364,
    originalPrice: 6970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m35-.jpg",
    description:
      "Galaxy M35 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 6000mAh.",
    rating: 4.9,
    reviews: 111,
    discount: 12,
    isHot: false,
  },
  {
    id: 73,
    name: "Galaxy Tab S6 Lite (2024)",
    brand: "Samsung",
    brandId: "samsung",
    price: 12334400,
    originalPrice: 13860000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s6-lite-2024.jpg",
    description:
      "Galaxy Tab S6 Lite (2024) là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 7040mAh.",
    rating: 5,
    reviews: 409,
    discount: 11,
    isHot: false,
  },
  {
    id: 74,
    name: "Galaxy M15",
    brand: "Samsung",
    brandId: "samsung",
    price: 4525799,
    originalPrice: 5590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m15.jpg",
    description:
      "Galaxy M15 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.0,
    reviews: 291,
    discount: 19,
    isHot: true,
  },
  {
    id: 75,
    name: "Galaxy Watch Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 10264996,
    originalPrice: 14660000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch-ultra.jpg",
    description:
      "Galaxy Watch Ultra là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 2GB và pin 590mAh.",
    rating: 4.3,
    reviews: 119,
    discount: 30,
    isHot: false,
  },
  {
    id: 76,
    name: "Galaxy S25 Edge",
    brand: "Samsung",
    brandId: "samsung",
    price: 22762210,
    originalPrice: 28810000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-edge.jpg",
    description:
      "Galaxy S25 Edge là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 3900mAh.",
    rating: 4.7,
    reviews: 29,
    discount: 21,
    isHot: true,
  },
  {
    id: 77,
    name: "Galaxy XCover7 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 16512369,
    originalPrice: 19200000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover7-pro-1.jpg",
    description:
      "Galaxy XCover7 Pro là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 4350mAh.",
    rating: 4.7,
    reviews: 299,
    discount: 14,
    isHot: true,
  },
  {
    id: 78,
    name: "Galaxy S25+",
    brand: "Samsung",
    brandId: "samsung",
    price: 23435051,
    originalPrice: 28930000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s25-plus-sm-s936.jpg",
    description:
      "Galaxy S25+ là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4900mAh.",
    rating: 5,
    reviews: 100,
    discount: 19,
    isHot: true,
  },
  {
    id: 79,
    name: "Galaxy S24 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 12334091,
    originalPrice: 17130000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-fe-r1.jpg",
    description:
      "Galaxy S24 FE là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4700mAh.",
    rating: 4.3,
    reviews: 408,
    discount: 28,
    isHot: false,
  },
  {
    id: 80,
    name: "Galaxy A16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3551998,
    originalPrice: 4440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-lte.jpg",
    description:
      "Galaxy A16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 53,
    discount: 20,
    isHot: true,
  },
  {
    id: 81,
    name: "Galaxy Tab S10 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 17884880,
    originalPrice: 19650000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s10-fe.jpg",
    description:
      "Galaxy Tab S10 FE là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 8GB và pin 8000mAh.",
    rating: 5,
    reviews: 394,
    discount: 9,
    isHot: false,
  },
  {
    id: 82,
    name: "Galaxy Z Fold7",
    brand: "Samsung",
    brandId: "samsung",
    price: 43711571,
    originalPrice: 51430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold7.jpg",
    description:
      "Galaxy Z Fold7 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 5,
    reviews: 458,
    discount: 15,
    isHot: false,
  },
  {
    id: 83,
    name: "Galaxy M56",
    brand: "Samsung",
    brandId: "samsung",
    price: 8162828,
    originalPrice: 8970000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m56-5g.jpg",
    description:
      "Galaxy M56 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 5,
    reviews: 380,
    discount: 9,
    isHot: true,
  },
  {
    id: 84,
    name: "Galaxy F14 4G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3083600,
    originalPrice: 4410000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f14-4g.jpg",
    description:
      "Galaxy F14 4G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 331,
    discount: 30,
    isHot: true,
  },
  {
    id: 85,
    name: "Galaxy F05",
    brand: "Samsung",
    brandId: "samsung",
    price: 1900840,
    originalPrice: 2160000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f05.jpg",
    description:
      "Galaxy F05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 448,
    discount: 12,
    isHot: false,
  },
  {
    id: 86,
    name: "Galaxy A35",
    brand: "Samsung",
    brandId: "samsung",
    price: 7308132,
    originalPrice: 7770000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg",
    description:
      "Galaxy A35 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 151,
    discount: 6,
    isHot: false,
  },
  {
    id: 87,
    name: "Galaxy A55",
    brand: "Samsung",
    brandId: "samsung",
    price: 10416092,
    originalPrice: 11570000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg",
    description:
      "Galaxy A55 là điện thoại cao cấp nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 86,
    discount: 10,
    isHot: true,
  },
  {
    id: 88,
    name: "Galaxy Z Fold6",
    brand: "Samsung",
    brandId: "samsung",
    price: 23976531,
    originalPrice: 25510000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold6.jpg",
    description:
      "Galaxy Z Fold6 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.1,
    reviews: 328,
    discount: 6,
    isHot: true,
  },
  {
    id: 89,
    name: "Galaxy Watch8 Classic",
    brand: "Samsung",
    brandId: "samsung",
    price: 15769838,
    originalPrice: 16600000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch8-classic.jpg",
    description:
      "Galaxy Watch8 Classic là điện thoại cao cấp nổi bật với màn hình OLED sống động. Máy được trang bị RAM 2GB và pin 445mAh.",
    rating: 4.2,
    reviews: 253,
    discount: 5,
    isHot: true,
  },
  {
    id: 90,
    name: "Galaxy Tab S10+",
    brand: "Samsung",
    brandId: "samsung",
    price: 23843824,
    originalPrice: 29440000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s10-plus.jpg",
    description:
      "Galaxy Tab S10+ là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 10090mAh.",
    rating: 5,
    reviews: 53,
    discount: 19,
    isHot: true,
  },
  {
    id: 91,
    name: "Galaxy F06 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3031724,
    originalPrice: 3330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f06-5g.jpg",
    description:
      "Galaxy F06 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 66,
    discount: 9,
    isHot: false,
  },
  {
    id: 92,
    name: "Galaxy A06",
    brand: "Samsung",
    brandId: "samsung",
    price: 2774931,
    originalPrice: 3600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-1.jpg",
    description:
      "Galaxy A06 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 324,
    discount: 23,
    isHot: true,
  },
  {
    id: 93,
    name: "Galaxy A16 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4307480,
    originalPrice: 5670000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a16-5g.jpg",
    description:
      "Galaxy A16 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 210,
    discount: 24,
    isHot: true,
  },
  {
    id: 94,
    name: "Galaxy F55",
    brand: "Samsung",
    brandId: "samsung",
    price: 5166088,
    originalPrice: 6220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f55.jpg",
    description:
      "Galaxy F55 là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 20,
    discount: 17,
    isHot: false,
  },
  {
    id: 95,
    name: "Galaxy M55s",
    brand: "Samsung",
    brandId: "samsung",
    price: 5171336,
    originalPrice: 6230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m55s.jpg",
    description:
      "Galaxy M55s là điện thoại tầm trung nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 73,
    discount: 17,
    isHot: true,
  },
  {
    id: 96,
    name: "Galaxy M16",
    brand: "Samsung",
    brandId: "samsung",
    price: 3352418,
    originalPrice: 4470000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m16-5g-.jpg",
    description:
      "Galaxy M16 là điện thoại giá rẻ nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 429,
    discount: 25,
    isHot: false,
  },
  {
    id: 97,
    name: "Galaxy M05",
    brand: "Samsung",
    brandId: "samsung",
    price: 1894718,
    originalPrice: 2080000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m05.jpg",
    description:
      "Galaxy M05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 438,
    discount: 9,
    isHot: false,
  },
  {
    id: 98,
    name: "Galaxy Z Flip7 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 28878839,
    originalPrice: 34790000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip7-fe-.jpg",
    description:
      "Galaxy Z Flip7 FE là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 5,
    reviews: 89,
    discount: 17,
    isHot: false,
  },
  {
    id: 99,
    name: "Galaxy A06 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3060878,
    originalPrice: 3980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a06-5g.jpg",
    description:
      "Galaxy A06 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 351,
    discount: 23,
    isHot: true,
  },
  {
    id: 100,
    name: "Galaxy Z Fold Special",
    brand: "Samsung",
    brandId: "samsung",
    price: 57663320,
    originalPrice: 64070000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold-special-edition.jpg",
    description:
      "Galaxy Z Fold Special là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 16GB và pin 4400mAh.",
    rating: 4.8,
    reviews: 89,
    discount: 10,
    isHot: true,
  },
  {
    id: 101,
    name: "Galaxy A36",
    brand: "Samsung",
    brandId: "samsung",
    price: 6953209,
    originalPrice: 9520000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a36.jpg",
    description:
      "Galaxy A36 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 157,
    discount: 27,
    isHot: false,
  },
  {
    id: 102,
    name: "Galaxy Tab Active5",
    brand: "Samsung",
    brandId: "samsung",
    price: 14801280,
    originalPrice: 18050000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-active5.jpg",
    description:
      "Galaxy Tab Active5 là điện thoại cao cấp nổi bật với pin cả ngày, màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 5050mAh.",
    rating: 4.2,
    reviews: 99,
    discount: 18,
    isHot: false,
  },
  {
    id: 103,
    name: "Galaxy A15",
    brand: "Samsung",
    brandId: "samsung",
    price: 4902924,
    originalPrice: 5840000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15-lte-.jpg",
    description:
      "Galaxy A15 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 373,
    discount: 16,
    isHot: false,
  },
  {
    id: 104,
    name: "Galaxy S24",
    brand: "Samsung",
    brandId: "samsung",
    price: 13321152,
    originalPrice: 15670000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg",
    description:
      "Galaxy S24 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 4.9,
    reviews: 167,
    discount: 15,
    isHot: true,
  },
  {
    id: 105,
    name: "Galaxy Tab S9 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 8506264,
    originalPrice: 9250000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-fe-10-.jpg",
    description:
      "Galaxy Tab S9 FE là điện thoại tầm trung nổi bật với thời lượng pin khủng. Máy được trang bị RAM 6GB và pin 8000mAh.",
    rating: 4.2,
    reviews: 393,
    discount: 8,
    isHot: false,
  },
  {
    id: 106,
    name: "Galaxy Watch6 Classic",
    brand: "Samsung",
    brandId: "samsung",
    price: 7101530,
    originalPrice: 7800000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6-classic.jpg",
    description:
      "Galaxy Watch6 Classic là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 2GB và pin 425mAh.",
    rating: 4.8,
    reviews: 301,
    discount: 9,
    isHot: false,
  },
  {
    id: 107,
    name: "Galaxy A34",
    brand: "Samsung",
    brandId: "samsung",
    price: 5735496,
    originalPrice: 6440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a34.jpg",
    description:
      "Galaxy A34 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 447,
    discount: 11,
    isHot: false,
  },
  {
    id: 108,
    name: "Galaxy A14",
    brand: "Samsung",
    brandId: "samsung",
    price: 3778643,
    originalPrice: 4150000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a14-4g.jpg",
    description:
      "Galaxy A14 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 182,
    discount: 9,
    isHot: true,
  },
  {
    id: 109,
    name: "Galaxy M34 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7060000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m34-5g.jpg",
    description:
      "Galaxy M34 5G là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 476,
    discount: 17,
    isHot: true,
  },
  {
    id: 110,
    name: "Galaxy Tab S9+",
    brand: "Samsung",
    brandId: "samsung",
    price: 30836000,
    originalPrice: 42240000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-plus-5g.jpg",
    description:
      "Galaxy Tab S9+ là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 10090mAh.",
    rating: 4.4,
    reviews: 441,
    discount: 27,
    isHot: true,
  },
  {
    id: 111,
    name: "Galaxy A14 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4594255,
    originalPrice: 6560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a14-5g.jpg",
    description:
      "Galaxy A14 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 24,
    discount: 30,
    isHot: false,
  },
  {
    id: 112,
    name: "Galaxy M54",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m54-5g.jpg",
    description:
      "Galaxy M54 là điện thoại tầm trung nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 211,
    discount: 24,
    isHot: true,
  },
  {
    id: 113,
    name: "Galaxy Tab S9",
    brand: "Samsung",
    brandId: "samsung",
    price: 12547260,
    originalPrice: 14590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-5g.jpg",
    description:
      "Galaxy Tab S9 là điện thoại cao cấp nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 8400mAh.",
    rating: 4.4,
    reviews: 468,
    discount: 14,
    isHot: true,
  },
  {
    id: 114,
    name: "Galaxy S23 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 16016218,
    originalPrice: 17800000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-ultra-5g.jpg",
    description:
      "Galaxy S23 Ultra là điện thoại cao cấp nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 139,
    discount: 10,
    isHot: false,
  },
  {
    id: 115,
    name: "Galaxy F14",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 5710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f14.jpg",
    description:
      "Galaxy F14 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 293,
    discount: 19,
    isHot: false,
  },
  {
    id: 116,
    name: "Galaxy A23 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 4370694,
    originalPrice: 4600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23-5g.jpg",
    description:
      "Galaxy A23 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 255,
    discount: 5,
    isHot: true,
  },
  {
    id: 117,
    name: "Galaxy A04",
    brand: "Samsung",
    brandId: "samsung",
    price: 2288589,
    originalPrice: 2690000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04.jpg",
    description:
      "Galaxy A04 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 5,
    reviews: 390,
    discount: 15,
    isHot: true,
  },
  {
    id: 118,
    name: "Galaxy Z Flip4",
    brand: "Samsung",
    brandId: "samsung",
    price: 9374144,
    originalPrice: 12840000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip4-5g.jpg",
    description:
      "Galaxy Z Flip4 là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 5,
    reviews: 98,
    discount: 27,
    isHot: true,
  },
  {
    id: 119,
    name: "Galaxy S23+",
    brand: "Samsung",
    brandId: "samsung",
    price: 12519416,
    originalPrice: 13180000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-plus-5g.jpg",
    description:
      "Galaxy S23+ là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4700mAh.",
    rating: 5,
    reviews: 115,
    discount: 5,
    isHot: true,
  },
  {
    id: 120,
    name: "Galaxy Z Fold4",
    brand: "Samsung",
    brandId: "samsung",
    price: 15784640,
    originalPrice: 17350000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold4.jpg",
    description:
      "Galaxy Z Fold4 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.8,
    reviews: 298,
    discount: 9,
    isHot: true,
  },
  {
    id: 121,
    name: "Galaxy Tab A7 10.4 (2022)",
    brand: "Samsung",
    brandId: "samsung",
    price: 7709000,
    originalPrice: 10420000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a7-104-2020.jpg",
    description:
      "Galaxy Tab A7 10.4 (2022) là điện thoại tầm trung nổi bật với thời lượng pin khủng. Máy được trang bị RAM 3GB và pin 7040mAh.",
    rating: 5,
    reviews: 29,
    discount: 26,
    isHot: false,
  },
  {
    id: 122,
    name: "Galaxy M14 4G",
    brand: "Samsung",
    brandId: "samsung",
    price: 2332028,
    originalPrice: 3070000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m14-4g.jpg",
    description:
      "Galaxy M14 4G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 436,
    discount: 24,
    isHot: true,
  },
  {
    id: 123,
    name: "Galaxy Z Fold5",
    brand: "Samsung",
    brandId: "samsung",
    price: 23073345,
    originalPrice: 24550000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold5-5g.jpg",
    description:
      "Galaxy Z Fold5 là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 4.7,
    reviews: 303,
    discount: 6,
    isHot: true,
  },
  {
    id: 124,
    name: "Galaxy S23 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 11738956,
    originalPrice: 16530000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-fe.jpg",
    description:
      "Galaxy S23 FE là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 5,
    reviews: 307,
    discount: 29,
    isHot: false,
  },
  {
    id: 125,
    name: "Galaxy M14",
    brand: "Samsung",
    brandId: "samsung",
    price: 6167200,
    originalPrice: 7610000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m14-5g-sm-m146.jpg",
    description:
      "Galaxy M14 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 384,
    discount: 19,
    isHot: true,
  },
  {
    id: 126,
    name: "Galaxy F54",
    brand: "Samsung",
    brandId: "samsung",
    price: 10484240,
    originalPrice: 13980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f54-5g.jpg",
    description:
      "Galaxy F54 là điện thoại cao cấp nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 6000mAh.",
    rating: 4.3,
    reviews: 193,
    discount: 25,
    isHot: false,
  },
  {
    id: 127,
    name: "Galaxy Z Flip5",
    brand: "Samsung",
    brandId: "samsung",
    price: 16581442,
    originalPrice: 18630000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip5-5g.jpg",
    description:
      "Galaxy Z Flip5 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 5,
    reviews: 215,
    discount: 11,
    isHot: false,
  },
  {
    id: 128,
    name: "Galaxy Watch5",
    brand: "Samsung",
    brandId: "samsung",
    price: 5242120,
    originalPrice: 5580000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch5.jpg",
    description:
      "Galaxy Watch5 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 5GB và pin 410mAh.",
    rating: 5,
    reviews: 96,
    discount: 6,
    isHot: false,
  },
  {
    id: 129,
    name: "Galaxy F15",
    brand: "Samsung",
    brandId: "samsung",
    price: 3789728,
    originalPrice: 5050000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f15-5g.jpg",
    description:
      "Galaxy F15 là điện thoại giá rẻ nổi bật với thời lượng pin khủng, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.1,
    reviews: 257,
    discount: 25,
    isHot: true,
  },
  {
    id: 130,
    name: "Galaxy A54",
    brand: "Samsung",
    brandId: "samsung",
    price: 5816286,
    originalPrice: 7090000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a54.jpg",
    description:
      "Galaxy A54 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 330,
    discount: 18,
    isHot: false,
  },
  {
    id: 131,
    name: "Galaxy A04s",
    brand: "Samsung",
    brandId: "samsung",
    price: 3188442,
    originalPrice: 3430000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04s.jpg",
    description:
      "Galaxy A04s là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 55,
    discount: 7,
    isHot: false,
  },
  {
    id: 132,
    name: "Galaxy Tab Active4 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 25593880,
    originalPrice: 34130000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-active4-pro.jpg",
    description:
      "Galaxy Tab Active4 Pro là điện thoại flagship nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 7600mAh.",
    rating: 4.0,
    reviews: 489,
    discount: 25,
    isHot: false,
  },
  {
    id: 133,
    name: "Galaxy A05",
    brand: "Samsung",
    brandId: "samsung",
    price: 2291232,
    originalPrice: 2980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a05.jpg",
    description:
      "Galaxy A05 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 218,
    discount: 23,
    isHot: true,
  },
  {
    id: 134,
    name: "Galaxy A25",
    brand: "Samsung",
    brandId: "samsung",
    price: 6760176,
    originalPrice: 8240000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a25.jpg",
    description:
      "Galaxy A25 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 96,
    discount: 18,
    isHot: true,
  },
  {
    id: 135,
    name: "Galaxy XCover7",
    brand: "Samsung",
    brandId: "samsung",
    price: 7215624,
    originalPrice: 10310000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover7.jpg",
    description:
      "Galaxy XCover7 là điện thoại tầm trung nổi bật với camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4050mAh.",
    rating: 5,
    reviews: 144,
    discount: 30,
    isHot: true,
  },
  {
    id: 136,
    name: "Galaxy Watch6",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7060000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch6.jpg",
    description:
      "Galaxy Watch6 là điện thoại tầm trung nổi bật với màn hình OLED sống động. Máy được trang bị RAM 2GB và pin 425mAh.",
    rating: 5,
    reviews: 101,
    discount: 17,
    isHot: true,
  },
  {
    id: 137,
    name: "Galaxy Tab A9",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 7600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a9.jpg",
    description:
      "Galaxy Tab A9 là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5100mAh.",
    rating: 5,
    reviews: 185,
    discount: 27,
    isHot: false,
  },
  {
    id: 138,
    name: "Galaxy Tab S9 FE+",
    brand: "Samsung",
    brandId: "samsung",
    price: 21828804,
    originalPrice: 29500000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-fe-plus-10-.jpg",
    description:
      "Galaxy Tab S9 FE+ là điện thoại flagship nổi bật với thời lượng pin khủng. Máy được trang bị RAM 6GB và pin 10090mAh.",
    rating: 4.4,
    reviews: 222,
    discount: 26,
    isHot: true,
  },
  {
    id: 139,
    name: "Galaxy Tab S9 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 37003200,
    originalPrice: 48690000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-ultra-5g.jpg",
    description:
      "Galaxy Tab S9 Ultra là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 11200mAh.",
    rating: 5,
    reviews: 462,
    discount: 24,
    isHot: false,
  },
  {
    id: 140,
    name: "Galaxy Watch5 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 3391960,
    originalPrice: 3900000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch5pro.jpg",
    description:
      "Galaxy Watch5 Pro là điện thoại giá rẻ nổi bật với màn hình OLED sống động. Máy được trang bị RAM 5GB và pin 590mAh.",
    rating: 5,
    reviews: 314,
    discount: 13,
    isHot: false,
  },
  {
    id: 141,
    name: "Galaxy A15 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5241811,
    originalPrice: 5890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a15-5g-new.jpg",
    description:
      "Galaxy A15 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 312,
    discount: 11,
    isHot: true,
  },
  {
    id: 142,
    name: "Galaxy M04",
    brand: "Samsung",
    brandId: "samsung",
    price: 3083600,
    originalPrice: 4340000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m04-.jpg",
    description:
      "Galaxy M04 là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 185,
    discount: 29,
    isHot: false,
  },
  {
    id: 143,
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 21196974,
    originalPrice: 27530000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-stylus.jpg",
    description:
      "Galaxy S24 Ultra là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 5,
    reviews: 500,
    discount: 23,
    isHot: false,
  },
  {
    id: 144,
    name: "Galaxy S23",
    brand: "Samsung",
    brandId: "samsung",
    price: 10792600,
    originalPrice: 11990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-5g.jpg",
    description:
      "Galaxy S23 là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 3900mAh.",
    rating: 5,
    reviews: 88,
    discount: 10,
    isHot: true,
  },
  {
    id: 145,
    name: "Galaxy A04e",
    brand: "Samsung",
    brandId: "samsung",
    price: 3160056,
    originalPrice: 3590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a04e.jpg",
    description:
      "Galaxy A04e là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 210,
    discount: 12,
    isHot: false,
  },
  {
    id: 146,
    name: "Galaxy A05s",
    brand: "Samsung",
    brandId: "samsung",
    price: 3310552,
    originalPrice: 3480000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a05s.jpg",
    description:
      "Galaxy A05s là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 499,
    discount: 5,
    isHot: true,
  },
  {
    id: 147,
    name: "Galaxy S24+",
    brand: "Samsung",
    brandId: "samsung",
    price: 18408783,
    originalPrice: 21920000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-plus-5g-sm-s926.jpg",
    description:
      "Galaxy S24+ là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 12GB và pin 4900mAh.",
    rating: 5,
    reviews: 278,
    discount: 16,
    isHot: true,
  },
  {
    id: 148,
    name: "Galaxy S20 FE 2022",
    brand: "Samsung",
    brandId: "samsung",
    price: 16034720,
    originalPrice: 22580000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-fe-5g.jpg",
    description:
      "Galaxy S20 FE 2022 là điện thoại cao cấp nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4500mAh.",
    rating: 4.8,
    reviews: 58,
    discount: 29,
    isHot: false,
  },
  {
    id: 149,
    name: "Galaxy A13 (SM-A137)",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 7710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13-a137.jpg",
    description:
      "Galaxy A13 (SM-A137) là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 23,
    discount: 28,
    isHot: false,
  },
  {
    id: 150,
    name: "Galaxy S22 Ultra 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 10083372,
    originalPrice: 10730000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-ultra-5g.jpg",
    description:
      "Galaxy S22 Ultra 5G là điện thoại cao cấp nổi bật với pin cả ngày, hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 61,
    discount: 6,
    isHot: false,
  },
  {
    id: 151,
    name: "Galaxy S22+ 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8603244,
    originalPrice: 12120000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-plus-5g.jpg",
    description:
      "Galaxy S22+ 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 4.0,
    reviews: 443,
    discount: 29,
    isHot: true,
  },
  {
    id: 152,
    name: "Galaxy A23",
    brand: "Samsung",
    brandId: "samsung",
    price: 6122048,
    originalPrice: 7120000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23.jpg",
    description:
      "Galaxy A23 là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 52,
    discount: 14,
    isHot: true,
  },
  {
    id: 153,
    name: "Galaxy M22",
    brand: "Samsung",
    brandId: "samsung",
    price: 7092280,
    originalPrice: 8760000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m22-.jpg",
    description:
      "Galaxy M22 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 373,
    discount: 19,
    isHot: true,
  },
  {
    id: 154,
    name: "Galaxy A12 (India)",
    brand: "Samsung",
    brandId: "samsung",
    price: 4933760,
    originalPrice: 5940000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-sm-a125.jpg",
    description:
      "Galaxy A12 (India) là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 193,
    discount: 17,
    isHot: true,
  },
  {
    id: 155,
    name: "Galaxy Watch4 Classic",
    brand: "Samsung",
    brandId: "samsung",
    price: 2775240,
    originalPrice: 3260000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch4-classic.jpg",
    description:
      "Galaxy Watch4 Classic là điện thoại giá rẻ nổi bật với màn hình OLED sống động. Máy được trang bị RAM 5GB và pin 361mAh.",
    rating: 4.8,
    reviews: 310,
    discount: 15,
    isHot: false,
  },
  {
    id: 156,
    name: "Galaxy F52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017360,
    originalPrice: 9110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f52-5g.jpg",
    description:
      "Galaxy F52 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 4500mAh.",
    rating: 4.2,
    reviews: 357,
    discount: 12,
    isHot: false,
  },
  {
    id: 157,
    name: "Galaxy A03",
    brand: "Samsung",
    brandId: "samsung",
    price: 4100879,
    originalPrice: 5330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03.jpg",
    description:
      "Galaxy A03 là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 263,
    discount: 23,
    isHot: false,
  },
  {
    id: 158,
    name: "Galaxy Tab A7 Lite",
    brand: "Samsung",
    brandId: "samsung",
    price: 4317040,
    originalPrice: 4590000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a7-lite.jpg",
    description:
      "Galaxy Tab A7 Lite là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5100mAh.",
    rating: 5,
    reviews: 66,
    discount: 6,
    isHot: true,
  },
  {
    id: 159,
    name: "Galaxy Tab S6 Lite (2022)",
    brand: "Samsung",
    brandId: "samsung",
    price: 12334400,
    originalPrice: 13120000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/galaxy-tab-s6-lite-2022-lte-sm-p619-.jpg",
    description:
      "Galaxy Tab S6 Lite (2022) là điện thoại cao cấp nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 7040mAh.",
    rating: 4.8,
    reviews: 104,
    discount: 6,
    isHot: true,
  },
  {
    id: 160,
    name: "Galaxy Tab A8 10.5 (2021)",
    brand: "Samsung",
    brandId: "samsung",
    price: 7092280,
    originalPrice: 9460000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a8-105-2021-new.jpg",
    description:
      "Galaxy Tab A8 10.5 (2021) là điện thoại tầm trung nổi bật với thời lượng pin khủng. Máy được trang bị RAM 2GB và pin 7040mAh.",
    rating: 4.6,
    reviews: 284,
    discount: 25,
    isHot: false,
  },
  {
    id: 161,
    name: "Galaxy Tab S8",
    brand: "Samsung",
    brandId: "samsung",
    price: 10792600,
    originalPrice: 11480000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s8.jpg",
    description:
      "Galaxy Tab S8 là điện thoại cao cấp nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 8000mAh.",
    rating: 4.3,
    reviews: 74,
    discount: 6,
    isHot: true,
  },
  {
    id: 162,
    name: "Galaxy Tab S8 Ultra",
    brand: "Samsung",
    brandId: "samsung",
    price: 35461400,
    originalPrice: 42720000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s8-ultra.jpg",
    description:
      "Galaxy Tab S8 Ultra là điện thoại flagship nổi bật với thời lượng pin khủng, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 11200mAh.",
    rating: 5,
    reviews: 471,
    discount: 17,
    isHot: false,
  },
  {
    id: 163,
    name: "Galaxy A13 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3946082,
    originalPrice: 4340000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13-5g-.jpg",
    description:
      "Galaxy A13 5G là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 107,
    discount: 9,
    isHot: false,
  },
  {
    id: 164,
    name: "Galaxy A03s",
    brand: "Samsung",
    brandId: "samsung",
    price: 1817184,
    originalPrice: 2110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03s.jpg",
    description:
      "Galaxy A03s là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 5,
    reviews: 466,
    discount: 14,
    isHot: true,
  },
  {
    id: 165,
    name: "Galaxy M52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 9250800,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32-5g-.jpg",
    description:
      "Galaxy M52 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 266,
    discount: 20,
    isHot: false,
  },
  {
    id: 166,
    name: "Galaxy M13 (India)",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 6010000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13-4g-india.jpg",
    description:
      "Galaxy M13 (India) là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.5,
    reviews: 260,
    discount: 23,
    isHot: false,
  },
  {
    id: 167,
    name: "Galaxy Watch4",
    brand: "Samsung",
    brandId: "samsung",
    price: 3391960,
    originalPrice: 4040000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch4.jpg",
    description:
      "Galaxy Watch4 là điện thoại giá rẻ nổi bật với màn hình OLED sống động. Máy được trang bị RAM 5GB và pin 361mAh.",
    rating: 4.5,
    reviews: 67,
    discount: 16,
    isHot: true,
  },
  {
    id: 168,
    name: "Galaxy A22 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 3414470,
    originalPrice: 4740000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a22-5g.jpg",
    description:
      "Galaxy A22 5G là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.3,
    reviews: 230,
    discount: 28,
    isHot: false,
  },
  {
    id: 169,
    name: "Galaxy A13",
    brand: "Samsung",
    brandId: "samsung",
    price: 3511912,
    originalPrice: 3900000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13.jpg",
    description:
      "Galaxy A13 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 407,
    discount: 10,
    isHot: false,
  },
  {
    id: 170,
    name: "Galaxy F23",
    brand: "Samsung",
    brandId: "samsung",
    price: 5858840,
    originalPrice: 7230000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m23.jpg",
    description:
      "Galaxy F23 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 391,
    discount: 19,
    isHot: false,
  },
  {
    id: 171,
    name: "Galaxy M32 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6783920,
    originalPrice: 7140000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32-5g-new.jpg",
    description:
      "Galaxy M32 5G là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.4,
    reviews: 110,
    discount: 5,
    isHot: false,
  },
  {
    id: 172,
    name: "Galaxy M53",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017051,
    originalPrice: 8440000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m53-5g.jpg",
    description:
      "Galaxy M53 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 209,
    discount: 5,
    isHot: true,
  },
  {
    id: 173,
    name: "Galaxy A12 Nacho",
    brand: "Samsung",
    brandId: "samsung",
    price: 4008680,
    originalPrice: 4890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-nacho.jpg",
    description:
      "Galaxy A12 Nacho là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 269,
    discount: 18,
    isHot: false,
  },
  {
    id: 174,
    name: "Galaxy Tab S7 FE",
    brand: "Samsung",
    brandId: "samsung",
    price: 20043400,
    originalPrice: 23860000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s7-fe.jpg",
    description:
      "Galaxy Tab S7 FE là điện thoại flagship nổi bật với thời lượng pin khủng. Máy được trang bị RAM 4GB và pin 10090mAh.",
    rating: 5,
    reviews: 423,
    discount: 16,
    isHot: false,
  },
  {
    id: 175,
    name: "Galaxy A53 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6387677,
    originalPrice: 7020000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a53-5g-.jpg",
    description:
      "Galaxy A53 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.9,
    reviews: 482,
    discount: 9,
    isHot: true,
  },
  {
    id: 176,
    name: "Galaxy S22 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7061444,
    originalPrice: 8410000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-5g.jpg",
    description:
      "Galaxy S22 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà, camera độ phân giải cao. Máy được trang bị RAM 8GB và pin 3700mAh.",
    rating: 4.0,
    reviews: 253,
    discount: 16,
    isHot: false,
  },
  {
    id: 177,
    name: "Galaxy A52s 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8017360,
    originalPrice: 8620000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a52s-5g.jpg",
    description:
      "Galaxy A52s 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4500mAh.",
    rating: 5,
    reviews: 472,
    discount: 7,
    isHot: true,
  },
  {
    id: 178,
    name: "Galaxy M13",
    brand: "Samsung",
    brandId: "samsung",
    price: 3965509,
    originalPrice: 5510000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13.jpg",
    description:
      "Galaxy M13 là điện thoại giá rẻ nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 340,
    discount: 28,
    isHot: true,
  },
  {
    id: 179,
    name: "Galaxy S21 FE 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6475560,
    originalPrice: 7800000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg",
    description:
      "Galaxy S21 FE 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà. Máy được trang bị RAM 6GB và pin 4500mAh.",
    rating: 5,
    reviews: 134,
    discount: 17,
    isHot: true,
  },
  {
    id: 180,
    name: "Galaxy A22",
    brand: "Samsung",
    brandId: "samsung",
    price: 6136672,
    originalPrice: 8640000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a22.jpg",
    description:
      "Galaxy A22 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 25,
    discount: 29,
    isHot: true,
  },
  {
    id: 181,
    name: "Galaxy M42 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 6783920,
    originalPrice: 7290000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m42.jpg",
    description:
      "Galaxy M42 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.8,
    reviews: 249,
    discount: 7,
    isHot: true,
  },
  {
    id: 182,
    name: "Galaxy F22",
    brand: "Samsung",
    brandId: "samsung",
    price: 5242120,
    originalPrice: 5760000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f22.jpg",
    description:
      "Galaxy F22 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.6,
    reviews: 243,
    discount: 9,
    isHot: true,
  },
  {
    id: 183,
    name: "Galaxy F13",
    brand: "Samsung",
    brandId: "samsung",
    price: 4625400,
    originalPrice: 5080000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f13.jpg",
    description:
      "Galaxy F13 là điện thoại tầm trung nổi bật với thời lượng pin khủng, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.7,
    reviews: 346,
    discount: 9,
    isHot: false,
  },
  {
    id: 184,
    name: "Galaxy M32",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 6850000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m32.jpg",
    description:
      "Galaxy M32 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.0,
    reviews: 219,
    discount: 19,
    isHot: true,
  },
  {
    id: 185,
    name: "Galaxy M21 2021",
    brand: "Samsung",
    brandId: "samsung",
    price: 4008680,
    originalPrice: 4660000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m21-2021.jpg",
    description:
      "Galaxy M21 2021 là điện thoại tầm trung nổi bật với thời lượng pin khủng, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 6000mAh.",
    rating: 4.4,
    reviews: 75,
    discount: 14,
    isHot: true,
  },
  {
    id: 186,
    name: "Galaxy M12",
    brand: "Samsung",
    brandId: "samsung",
    price: 5242120,
    originalPrice: 6100000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m12.jpg",
    description:
      "Galaxy M12 là điện thoại tầm trung nổi bật với pin cả ngày. Máy được trang bị RAM 3GB và pin 5000mAh.",
    rating: 5,
    reviews: 22,
    discount: 14,
    isHot: false,
  },
  {
    id: 187,
    name: "Galaxy A33 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5116309,
    originalPrice: 7110000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a33-5g.jpg",
    description:
      "Galaxy A33 5G là điện thoại tầm trung nổi bật với pin cả ngày, màn hình OLED sống động. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.6,
    reviews: 450,
    discount: 28,
    isHot: true,
  },
  {
    id: 188,
    name: "Galaxy Z Flip3 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 8788260,
    originalPrice: 11560000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip3-5g.jpg",
    description:
      "Galaxy Z Flip3 5G là điện thoại tầm trung nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 3300mAh.",
    rating: 4.6,
    reviews: 342,
    discount: 24,
    isHot: false,
  },
  {
    id: 189,
    name: "Galaxy A03 Core",
    brand: "Samsung",
    brandId: "samsung",
    price: 1816920,
    originalPrice: 2000000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a03-core.jpg",
    description:
      "Galaxy A03 Core là điện thoại giá rẻ nổi bật với pin cả ngày. Máy được trang bị RAM 2GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 94,
    discount: 9,
    isHot: true,
  },
  {
    id: 190,
    name: "Galaxy Z Fold3 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 16959800,
    originalPrice: 23890000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold3-5g.jpg",
    description:
      "Galaxy Z Fold3 5G là điện thoại cao cấp nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 4400mAh.",
    rating: 5,
    reviews: 486,
    discount: 29,
    isHot: true,
  },
  {
    id: 191,
    name: "Galaxy F42 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7400640,
    originalPrice: 10280000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f42-5g.jpg",
    description:
      "Galaxy F42 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 4.5,
    reviews: 233,
    discount: 28,
    isHot: false,
  },
  {
    id: 192,
    name: "Galaxy M23",
    brand: "Samsung",
    brandId: "samsung",
    price: 6463842,
    originalPrice: 7600000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m23.jpg",
    description:
      "Galaxy M23 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 241,
    discount: 15,
    isHot: true,
  },
  {
    id: 193,
    name: "Galaxy M33",
    brand: "Samsung",
    brandId: "samsung",
    price: 8633771,
    originalPrice: 12330000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m33.jpg",
    description:
      "Galaxy M33 là điện thoại tầm trung nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 215,
    discount: 30,
    isHot: false,
  },
  {
    id: 194,
    name: "Galaxy M13 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 5550480,
    originalPrice: 6610000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m13-5g.jpg",
    description:
      "Galaxy M13 5G là điện thoại tầm trung nổi bật với pin cả ngày, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 5000mAh.",
    rating: 5,
    reviews: 312,
    discount: 16,
    isHot: true,
  },
  {
    id: 195,
    name: "Galaxy A73 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 18501600,
    originalPrice: 25000000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a73-5g.jpg",
    description:
      "Galaxy A73 5G là điện thoại cao cấp nổi bật với pin cả ngày, màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 5000mAh.",
    rating: 5,
    reviews: 331,
    discount: 26,
    isHot: true,
  },
  {
    id: 196,
    name: "Galaxy XCover6 Pro",
    brand: "Samsung",
    brandId: "samsung",
    price: 8940898,
    originalPrice: 10050000,
    image:
      "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover6-pro-r.jpg",
    description:
      "Galaxy XCover6 Pro là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 6GB và pin 4050mAh.",
    rating: 4.5,
    reviews: 29,
    discount: 11,
    isHot: true,
  },
  {
    id: 197,
    name: "Galaxy A52 5G",
    brand: "Samsung",
    brandId: "samsung",
    price: 7839127,
    originalPrice: 10740000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a52-5g.jpg",
    description:
      "Galaxy A52 5G là điện thoại tầm trung nổi bật với màn hình 120Hz mượt mà, camera độ phân giải cao. Máy được trang bị RAM 4GB và pin 4500mAh.",
    rating: 4.3,
    reviews: 21,
    discount: 27,
    isHot: true,
  },
  {
    id: 198,
    name: "Xperia 1 VI",
    brand: "Sony",
    brandId: "sony",
    price: 46099820,
    originalPrice: 54880000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-vi-red.jpg",
    description:
      "Xperia 1 VI là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 5000mAh.",
    rating: 4.2,
    reviews: 206,
    discount: 16,
    isHot: true,
  },
  {
    id: 199,
    name: "Xperia 5 IV",
    brand: "Sony",
    brandId: "sony",
    price: 26309664,
    originalPrice: 27990000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-iv-ofic.jpg",
    description:
      "Xperia 5 IV là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.7,
    reviews: 361,
    discount: 6,
    isHot: true,
  },
  {
    id: 200,
    name: "Xperia 5 V",
    brand: "Sony",
    brandId: "sony",
    price: 33735889,
    originalPrice: 36670000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-v-new.jpg",
    description:
      "Xperia 5 V là điện thoại flagship nổi bật với pin cả ngày, hiệu năng chơi game mượt mà. Máy được trang bị RAM 8GB và pin 5000mAh.",
    rating: 4.1,
    reviews: 453,
    discount: 8,
    isHot: true,
  },
  {
    id: 201,
    name: "Xperia XA1 Ultra",
    brand: "Sony",
    brandId: "sony",
    price: 7709000,
    originalPrice: 10710000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-xa1-ultra-2017.jpg",
    description:
      "Xperia XA1 Ultra là điện thoại tầm trung có thiết kế hiện đại, phù hợp cho nhu cầu hàng ngày. Máy được trang bị RAM 4GB và pin 2700mAh.",
    rating: 4.3,
    reviews: 372,
    discount: 28,
    isHot: false,
  },
  {
    id: 202,
    name: "Xperia Pro-I",
    brand: "Sony",
    brandId: "sony",
    price: 28677480,
    originalPrice: 32220000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-pro-i.jpg",
    description:
      "Xperia Pro-I là điện thoại flagship nổi bật với hiệu năng chơi game mượt mà. Máy được trang bị RAM 12GB và pin 4500mAh.",
    rating: 5,
    reviews: 52,
    discount: 11,
    isHot: false,
  },
  {
    id: 203,
    name: "Xperia 1 II",
    brand: "Sony",
    brandId: "sony",
    price: 21585200,
    originalPrice: 26980000,
    image: "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-II-o.jpg",
    description:
      "Xperia 1 II là điện thoại flagship nổi bật với màn hình OLED sống động. Máy được trang bị RAM 8GB và pin 4000mAh.",
    rating: 5,
    reviews: 491,
    discount: 20,
    isHot: false,
  },
];
